"""Prompt-based code editing: a code assistant that works on the files a person selects.

Like the coding assistants people use in an editor, it is an agent loop and not a single prompt. It lists folders, reads files, searches,
edits with exact replacements, writes and deletes files and checks syntax, one turn after another, and then reports. Everything it does
happens on an in-memory overlay of the workspace: nothing is written to the project until a person reviews the diff and applies it, and
an applied edit can be undone.

Two workspaces: the code the implementation stage generated (artefacts of the code stage) and the codebase a person uploaded. The
instructions are the `code-editor` agent file (agents/code/code-editor.md).
"""
from __future__ import annotations

import ast
import difflib
import hashlib
import json
import logging
import re
import time
from datetime import UTC, datetime
from typing import Any, Callable, Literal

from pydantic import BaseModel, Field

from ..domain.errors import SdlcError
from ..domain.models import UserPublic
from .agent_catalog import role_of
from .content_store import source_key
from .guardrails import enforce_input, sanitise_output
from .prompt_library import render as render_prompt
from .code_structure import is_test_path
from .stack import stack_of

log = logging.getLogger("code_edit")

MAX_STEPS = 14
MAX_CALLS = 6
MAX_READ_CHARS = 30_000
MAX_FILE_CHARS = 200_000
MAX_CHANGED = 25
MAX_LISTING = 300
CONTEXT_BUDGET = 140_000          # characters of conversation kept verbatim before older tool results are shortened
SCAN_BUDGET = 3_000_000           # characters a search may scan
CODE_TYPES = ("APP_CODE", "UNIT_TESTS")
Emit = Callable[[dict[str, Any]], None]


class ToolCall(BaseModel):
    tool: Literal["list_dir", "read_file", "search", "edit_file", "write_file", "delete_file", "check_syntax"]
    path: str = ""
    pattern: str = ""
    start: int | None = None
    end: int | None = None
    old_string: str = ""
    new_string: str = ""
    content: str = ""
    replace_all: bool = False


class AgentStep(BaseModel):
    message: str = ""
    calls: list[ToolCall] = Field(default_factory=list)
    done: bool = False
    summary: str = ""


def norm_path(p: str) -> str:
    parts = [x for x in (p or "").replace("\\", "/").split("/") if x not in ("", ".")]
    if any(x == ".." for x in parts):
        raise SdlcError("VALIDATION_FAILED", f"'{p}' is not a path inside the project")
    return "/".join(parts)


def diff_of(before: str, after: str, path: str) -> tuple[str, int, int]:
    """Unified diff, plus lines added and removed."""
    lines = list(difflib.unified_diff(before.splitlines(), after.splitlines(), f"a/{path}", f"b/{path}", n=3, lineterm=""))
    added = sum(1 for ln in lines if ln.startswith("+") and not ln.startswith("+++"))
    removed = sum(1 for ln in lines if ln.startswith("-") and not ln.startswith("---"))
    text = "\n".join(lines)
    return (text if len(text) <= 60_000 else text[:60_000] + "\n… (diff shortened)"), added, removed


# ---------------------------------------------------------------- workspaces
class Workspace:
    """Read side of one body of code. `files()` is {path: size}; `read` returns the text or None."""
    label = ""

    async def files(self) -> dict[str, int]:
        raise NotImplementedError

    async def read(self, path: str) -> str | None:
        raise NotImplementedError


class UploadedWorkspace(Workspace):
    label = "the uploaded codebase"

    def __init__(self, db: Any, project_id: str) -> None:
        self._db, self._pid = db, project_id
        self._rows: dict[str, dict] | None = None

    async def _load(self) -> dict[str, dict]:
        if self._rows is None:
            self._rows = {r["path"]: dict(r) for r in await self._db.list_codebase_files(self._pid)}
        return self._rows

    async def files(self) -> dict[str, int]:
        return {p: int(r["size_bytes"]) for p, r in (await self._load()).items()}

    async def read(self, path: str) -> str | None:
        r = (await self._load()).get(path)
        if r is None:
            return None
        full = await self._db.get_codebase_file(self._pid, r["id"])
        return full["content"] if full else None


class GeneratedWorkspace(Workspace):
    label = "the code generated by the implementation stage"

    def __init__(self, db: Any, content: Any, project_id: str, phase: int) -> None:
        self._db, self._content, self._pid, self._phase = db, content, project_id, phase
        self._rows: dict[str, dict] | None = None

    async def _load(self) -> dict[str, dict]:
        if self._rows is None:
            rows = await self._db.list_phase_artefacts(self._pid, self._phase)
            self._rows = {r["title"]: dict(r) for r in rows if r["type"] in CODE_TYPES and r["is_latest"]}
        return self._rows

    async def files(self) -> dict[str, int]:
        return {p: len(r.get("content") or "") for p, r in (await self._load()).items()}

    async def read(self, path: str) -> str | None:
        r = (await self._load()).get(path)
        if r is None:
            return None
        if r.get("storage_key"):
            stored = await self._content.get(r["storage_key"])
            if stored is not None:
                return stored
        return r.get("content") or ""

    async def row(self, path: str) -> dict | None:
        return (await self._load()).get(path)


# ---------------------------------------------------------------- the overlay the agent works on
class Overlay:
    """The workspace plus the agent's pending changes. `changes[path] = {action, before, after}`; before is the original text."""

    def __init__(self, base: Workspace, targets: list[str], changes: dict[str, dict] | None = None) -> None:
        self.base = base
        self.targets = [t for t in targets if t]
        self.changes: dict[str, dict] = {k: dict(v) for k, v in (changes or {}).items()}
        self._base_files: dict[str, int] | None = None
        self._cache: dict[str, str | None] = {}
        self.read_chars = 0

    async def base_files(self) -> dict[str, int]:
        if self._base_files is None:
            self._base_files = await self.base.files()
        return self._base_files

    async def files(self) -> dict[str, int]:
        out = dict(await self.base_files())
        for p, c in self.changes.items():
            if c["action"] == "delete":
                out.pop(p, None)
            else:
                out[p] = len(c["after"] or "")
        return out

    async def read(self, path: str) -> str | None:
        c = self.changes.get(path)
        if c is not None:
            return None if c["action"] == "delete" else c["after"]
        return await self._read_base(path)

    async def _read_base(self, path: str) -> str | None:
        if path not in self._cache:
            self._cache[path] = await self.base.read(path) if path in await self.base_files() else None
        return self._cache[path]

    # ---- scope
    def _dirs(self, files: dict[str, int]) -> tuple[set[str], set[str]]:
        tf, td = set(), set()
        for t in self.targets:
            (tf if t in files else td).add(t.rstrip("/"))
        return tf, td

    async def can_modify(self, path: str) -> bool:
        if not self.targets:
            return True
        files = await self.files()
        tf, td = self._dirs(files)
        return path in tf or any(path.startswith(d + "/") or d == "" for d in td)

    async def can_create(self, path: str) -> bool:
        if not self.targets:
            return True
        files = await self.files()
        tf, td = self._dirs(files)
        here = path.rsplit("/", 1)[0] if "/" in path else ""
        return any(path.startswith(d + "/") for d in td) or any((f.rsplit("/", 1)[0] if "/" in f else "") == here for f in tf)

    # ---- mutation
    async def put(self, path: str, new: str, *, create_ok: bool = True) -> str:
        existing = await self.read(path)
        if existing is None and not await self.base_has(path):
            action, before = "create", ""
        else:
            prior = self.changes.get(path)
            before = prior["before"] if prior else (existing or "")
            action = "modify" if (prior is None or prior["action"] != "create") else "create"
            if prior and prior["action"] == "delete":
                action = "modify"
        if len(new) > MAX_FILE_CHARS:
            raise SdlcError("VALIDATION_FAILED", f"{path} would be larger than {MAX_FILE_CHARS:,} characters")
        if path not in self.changes and len(self.changes) >= MAX_CHANGED:
            raise SdlcError("VALIDATION_FAILED", f"At most {MAX_CHANGED} files can change in one request")
        if action == "modify" and new == before:
            self.changes.pop(path, None)
            return "no change"
        self.changes[path] = {"action": action, "before": before, "after": new}
        return action

    async def base_has(self, path: str) -> bool:
        return path in await self.base_files()

    async def remove(self, path: str) -> None:
        prior = self.changes.get(path)
        if prior and prior["action"] == "create":
            self.changes.pop(path)
            return
        before = prior["before"] if prior else (await self._read_base(path) or "")
        if path not in self.changes and len(self.changes) >= MAX_CHANGED:
            raise SdlcError("VALIDATION_FAILED", f"At most {MAX_CHANGED} files can change in one request")
        self.changes[path] = {"action": "delete", "before": before, "after": None}


# ---------------------------------------------------------------- the tools
def _numbered(text: str, start: int, end: int | None) -> tuple[str, bool]:
    lines = text.splitlines()
    s = max(1, start)
    e = len(lines) if end is None else min(len(lines), end)
    out, used = [], 0
    for i in range(s, e + 1):
        row = f"{i}\t{lines[i - 1]}"
        used += len(row) + 1
        if used > MAX_READ_CHARS:
            return "\n".join(out), True
        out.append(row)
    return "\n".join(out), e < len(lines)


def check_syntax(path: str, text: str) -> str:
    ext = path.rsplit(".", 1)[-1].lower() if "." in path else ""
    try:
        if ext == "py":
            ast.parse(text)
        elif ext == "json":
            json.loads(text)
        elif ext in ("yml", "yaml"):
            import yaml
            list(yaml.safe_load_all(text))
        elif ext in ("xml", "pom", "xsd", "svg"):
            import xml.etree.ElementTree as ET
            ET.fromstring(text)
        else:
            return f"No syntax checker for .{ext or 'this'} files; review it by reading it."
    except SyntaxError as err:
        return f"Syntax error at line {err.lineno}: {err.msg}"
    except Exception as err:  # noqa: BLE001
        return f"Does not parse: {str(err)[:200]}"
    return "Parses without errors."


class Tools:
    def __init__(self, ov: Overlay) -> None:
        self.ov = ov

    async def run(self, c: ToolCall) -> tuple[str, bool, str]:
        """(result text for the model, ok, short label for the person)."""
        try:
            return await getattr(self, c.tool)(c)
        except SdlcError as err:
            return f"ERROR: {err.message}", False, f"{c.tool} failed"

    async def list_dir(self, c: ToolCall) -> tuple[str, bool, str]:
        d = norm_path(c.path)
        pre = f"{d}/" if d else ""
        dirs, files = set(), []
        for p in await self.ov.files():
            if p.startswith(pre):
                rest = p[len(pre):]
                (dirs.add(rest.split("/", 1)[0] + "/") if "/" in rest else files.append(rest))
        if not dirs and not files:
            return f"ERROR: no folder '{d}'", False, f"List {d or '/'}"
        return "\n".join(sorted(dirs) + sorted(files)), True, f"Listed {d or 'the root'}"

    async def read_file(self, c: ToolCall) -> tuple[str, bool, str]:
        p = norm_path(c.path)
        text = await self.ov.read(p)
        if text is None:
            return f"ERROR: no file '{p}'. Use list_dir or search to find the right path.", False, f"Read {p}"
        body, more = _numbered(text, c.start or 1, c.end)
        self.ov.read_chars += len(body)
        note = f"\n[more lines follow; call read_file again with start={(c.start or 1) + body.count(chr(10)) + 1}]" if more else ""
        return (body or "(empty file)") + note, True, f"Read {p}"

    async def search(self, c: ToolCall) -> tuple[str, bool, str]:
        try:
            rx = re.compile(c.pattern)
        except re.error as err:
            return f"ERROR: bad regular expression: {err}", False, f"Search {c.pattern[:40]}"
        scope = norm_path(c.path) if c.path else ""
        hits, scanned = [], 0
        for p in sorted(await self.ov.files()):
            if scope and not (p == scope or p.startswith(scope + "/")):
                continue
            text = await self.ov.read(p)
            if not text:
                continue
            scanned += len(text)
            if scanned > SCAN_BUDGET:
                hits.append("[search stopped: the workspace is too large to scan fully]")
                break
            for i, line in enumerate(text.splitlines(), 1):
                if rx.search(line):
                    hits.append(f"{p}:{i}: {line.strip()[:200]}")
                    if len(hits) >= 40:
                        hits.append("[more matches omitted; narrow the pattern or the path]")
                        return "\n".join(hits), True, f"Searched for {c.pattern[:40]}"
        return ("\n".join(hits) if hits else "No matches."), True, f"Searched for {c.pattern[:40]}"

    async def edit_file(self, c: ToolCall) -> tuple[str, bool, str]:
        p = norm_path(c.path)
        label = f"Edit {p}"
        text = await self.ov.read(p)
        if text is None:
            return f"ERROR: no file '{p}'. To create a file use write_file.", False, label
        if not await self.ov.can_modify(p):
            return f"ERROR: {p} is outside the files the person selected, so it is read-only. Say so in your summary.", False, label
        if not c.old_string:
            return "ERROR: old_string is empty. Give the exact text to replace, or use write_file for a whole file.", False, label
        if c.old_string == c.new_string:
            return "ERROR: old_string and new_string are identical.", False, label
        n = text.count(c.old_string)
        if n == 0:
            near = difflib.get_close_matches(c.old_string.strip().splitlines()[0] if c.old_string.strip() else "", [ln for ln in text.splitlines()], 1, 0.6)
            hint = f" The closest line is: {near[0].strip()[:160]!r}" if near else ""
            return f"ERROR: old_string was not found in {p} (it must match exactly, including indentation).{hint} Read the file again.", False, label
        if n > 1 and not c.replace_all:
            return f"ERROR: old_string appears {n} times in {p}. Include more surrounding lines to make it unique, or set replace_all.", False, label
        new = text.replace(c.old_string, c.new_string) if c.replace_all else text.replace(c.old_string, c.new_string, 1)
        new, masked = sanitise_output(new)
        what = await self.ov.put(p, new)
        d, a, r = diff_of(self.ov.changes.get(p, {}).get("before", text), new, p)
        return f"OK: edited {p} (+{a} -{r}).{' Secrets were masked.' if masked else ''}", True, f"Edited {p} (+{a} −{r})" if what != "no change" else f"No change in {p}"

    async def write_file(self, c: ToolCall) -> tuple[str, bool, str]:
        p = norm_path(c.path)
        label = f"Write {p}"
        exists = (await self.ov.read(p)) is not None
        if exists and not await self.ov.can_modify(p):
            return f"ERROR: {p} is outside the files the person selected, so it is read-only.", False, label
        if not exists and not await self.ov.can_create(p):
            return f"ERROR: a new file at {p} is outside the selected folders. New files go inside a selected folder or beside a selected file.", False, label
        new, masked = sanitise_output(c.content)
        what = await self.ov.put(p, new)
        ch = self.ov.changes.get(p)
        a = len(new.splitlines()) if what == "create" else diff_of(ch["before"], new, p)[1] if ch else 0
        return f"OK: {'created' if what == 'create' else 'wrote'} {p}.{' Secrets were masked.' if masked else ''}", True, f"{'Created' if what == 'create' else 'Wrote'} {p}"

    async def delete_file(self, c: ToolCall) -> tuple[str, bool, str]:
        p = norm_path(c.path)
        label = f"Delete {p}"
        if (await self.ov.read(p)) is None:
            return f"ERROR: no file '{p}'.", False, label
        if not await self.ov.can_modify(p):
            return f"ERROR: {p} is outside the files the person selected, so it is read-only.", False, label
        await self.ov.remove(p)
        return f"OK: deleted {p}.", True, label

    async def check_syntax(self, c: ToolCall) -> tuple[str, bool, str]:
        p = norm_path(c.path)
        text = await self.ov.read(p)
        if text is None:
            return f"ERROR: no file '{p}'.", False, f"Check {p}"
        res = check_syntax(p, text)
        return res, not res.startswith(("Syntax error", "Does not parse")), f"Checked {p}: {res.split('.')[0].split(':')[0][:40]}"


# ---------------------------------------------------------------- the service
def _is_test(path: str) -> bool:
    return is_test_path(path)


def _listing(files: dict[str, int], changes: dict[str, dict]) -> str:
    paths = sorted(files)
    shown = paths[:MAX_LISTING]
    marks = {p: (" (changed)" if p in changes else "") for p in shown}
    out = "\n".join(f"{p}{marks[p]}" for p in shown)
    return out + (f"\n… and {len(paths) - MAX_LISTING} more files; use list_dir and search to find them" if len(paths) > MAX_LISTING else "")


def change_view(path: str, ch: dict) -> dict[str, Any]:
    d, a, r = diff_of(ch["before"] or "", ch["after"] or "", path)
    return {"path": path, "action": ch["action"], "added": a, "removed": r, "diff": d}


class CodeEditService:
    def __init__(self, db: Any, content: Any, rag: Any, audit: Any, authz: Any, llm: Any, chat: Any, workflow: Any, dynamo: Any,
                 canon: Any = None, memory: Any = None) -> None:
        self._db, self._content, self._rag, self._audit, self._authz = db, content, rag, audit, authz
        self._llm, self._chat, self._workflow, self._dynamo, self._canon, self._memory = llm, chat, workflow, dynamo, canon, memory

    # ------------------------------------------------------------ access
    async def _code_stage(self, project_id: str) -> dict | None:
        wf = await self._workflow.view(project_id)
        return next((s for s in wf["stages"] if s.get("template") == 6), None)

    async def _authorise(self, project_id: str, scope: str, user: UserPublic) -> tuple[int | None, dict | None]:
        await self._authz.assert_project_access(project_id, user)
        if scope not in ("generated", "uploaded"):
            raise SdlcError("VALIDATION_FAILED", "scope must be 'generated' or 'uploaded'")
        stage = await self._code_stage(project_id)
        if stage is not None:
            ok = await self._chat.can_write_stage(project_id, int(stage["seq"]), user)
        else:
            project = await self._db.get_project(project_id) or {}
            ok = user.role == "SUPER_ADMIN" or (user.role == "PROJECT_MANAGER" and project.get("created_by") == user.id)
        if not ok:
            raise SdlcError("FORBIDDEN", "Editing code needs write permission on the implementation stage")
        if scope == "generated":
            if stage is None:
                raise SdlcError("VALIDATION_FAILED", "This project has no implementation stage, so there is no generated code")
            state = await self._dynamo.get_phase_state(project_id, int(stage["seq"]))
            if state and state["status"] == "APPROVED":
                raise SdlcError("GATE_CONFLICT", "The implementation stage is approved. Request changes on it first, then edit the code.")
        return (int(stage["seq"]) if stage else None), stage

    def _workspace(self, project_id: str, scope: str, phase: int | None) -> Workspace:
        return GeneratedWorkspace(self._db, self._content, project_id, phase or 0) if scope == "generated" else UploadedWorkspace(self._db, project_id)

    # ------------------------------------------------------------ the loop
    async def stream(self, *, project_id: str, user: UserPublic, scope: str, targets: list[str], prompt: str, session_id: str | None,
                     emit: Emit, is_disconnected: Callable[[], Any] | None = None) -> None:
        prompt = (prompt or "").strip()
        if not prompt:
            raise SdlcError("VALIDATION_FAILED", "Tell the assistant what to change")
        enforce_input(prompt, channel="code_edit")
        phase, _ = await self._authorise(project_id, scope, user)
        targets = [norm_path(t) for t in (targets or [])][:60]
        sess = await self._db.get_code_edit(project_id, session_id) if session_id else None
        if sess and (sess["user_id"] != user.id or sess["scope"] != scope):
            raise SdlcError("NOT_FOUND", "Session not found")
        if sess and sess["status"] in ("applied", "reverted", "discarded"):
            sess = None                 # a finished session starts a new one
        base = self._workspace(project_id, scope, phase)
        files = await base.files()
        if not files:
            raise SdlcError("NOT_FOUND", "There is no code here yet. " + ("Run the implementation stage first." if scope == "generated" else "Upload a codebase first."))
        unknown = [t for t in targets if t not in files and not any(f.startswith(t.rstrip("/") + "/") for f in files)]
        if unknown:
            raise SdlcError("NOT_FOUND", f"Not found in the workspace: {', '.join(unknown[:5])}")
        pending_changes = dict(sess["changes"]) if sess else {}
        ov = Overlay(base, list(dict.fromkeys([*((sess or {}).get("targets") or []), *targets])), pending_changes)
        sid = sess["id"] if sess else hashlib.sha1(f"{project_id}{time.time_ns()}".encode()).hexdigest()[:16]
        record = {"id": sid, "project_id": project_id, "scope": scope, "phase": phase, "user_id": user.id, "user_email": user.email,
                  "title": (sess["title"] if sess else prompt[:90]), "status": "proposed", "targets": ov.targets,
                  "messages": list(sess["messages"]) if sess else [], "changes": ov.changes, "applied": {}, "usage": dict(sess["usage"]) if sess else {}}
        emit({"type": "session", "id": sid, "scope": scope, "targets": ov.targets})

        rules = ""
        if self._canon is not None:
            try:
                rules = await self._canon.render_block(project_id, 6) or ""
            except Exception:  # noqa: BLE001
                rules = ""
        if self._memory is not None:
            try:
                mem, _ = await self._memory.block_for(project_id, user.id, 6, prompt)
                rules = f"{rules}\n\n{mem}".strip() if mem else rules
            except Exception:  # noqa: BLE001
                pass
        project = await self._db.get_project(project_id) or {}
        pend = ""
        if pending_changes:
            pend = "\n## Changes you already proposed in this conversation (still pending)\n" + "\n".join(f"- {c['action']} {p}" for p, c in pending_changes.items()) + "\n"
        system = render_prompt("policy.responsible_ai") + "\n\n" + render_prompt("code_edit.system", max_calls=MAX_CALLS)
        first = render_prompt(
            "code_edit.user", stack=stack_of(project) or "(not decided)", scope_label=base.label,
            targets="\n".join(f"- {t}" for t in ov.targets) or "(the whole codebase)", file_count=len(files),
            listing=_listing(await ov.files(), ov.changes), rules=(f"\n## Project rules\n{rules}\n" if rules else ""), pending=pend, request=prompt)
        convo: list[tuple[str, str]] = [("user", first)]
        # earlier turns of this session, so a follow-up ("also add tests") sees what was asked and said
        history = [(m["role"], m["text"]) for m in record["messages"] if m.get("text")][-6:]
        if history:
            convo = [("user", first.replace("## Request\n" + prompt, "## Earlier in this conversation\n" + "\n".join(f"{'Person' if r == 'user' else 'You'}: {t}" for r, t in history) + "\n\n## Request\n" + prompt))]
        tools = Tools(ov)
        steps_log: list[dict[str, Any]] = []
        record["messages"].append({"role": "user", "text": prompt, "at": datetime.now(UTC).isoformat()})
        summary, role = "", role_of("code-editor", "generate")
        usage = record["usage"]
        usage.setdefault("promptTokens", 0)
        usage.setdefault("completionTokens", 0)
        try:
            for n in range(1, MAX_STEPS + 1):
                if is_disconnected is not None and await is_disconnected():
                    summary = "Stopped."
                    break
                messages = [{"role": "system", "content": system, "cache": True}] + _compact(convo)
                try:
                    step, res = await self._llm.generate_json(
                        intent="generation", tag="code_edit", schema=AgentStep, messages=messages, temperature=0.1,
                        max_tokens=16_000, max_attempts=2, role=role)
                except SdlcError as err:
                    emit({"type": "error", "code": err.code, "message": f"The assistant could not continue: {err.message}"})
                    summary = "The assistant stopped early. What it had changed so far is below."
                    break
                usage["promptTokens"] += res.usage.get("promptTokens", 0)
                usage["completionTokens"] += res.usage.get("completionTokens", 0)
                usage["model"], usage["provider"] = res.model, res.provider
                if step.message:
                    emit({"type": "message", "text": step.message})
                convo.append(("assistant", step.model_dump_json(exclude_defaults=True)))
                if step.done or not step.calls:
                    summary = step.summary or step.message or "Done."
                    break
                results: list[str] = []
                for i, call in enumerate(step.calls[:MAX_CALLS], 1):
                    cid = f"{n}.{i}"
                    emit({"type": "tool", "id": cid, "tool": call.tool, "label": _running_label(call), "status": "running"})
                    text, ok, label = await tools.run(call)
                    emit({"type": "tool", "id": cid, "tool": call.tool, "label": label, "status": "done" if ok else "error", "detail": "" if ok else text[:200]})
                    if call.tool in ("edit_file", "write_file", "delete_file") and ok:
                        p = norm_path(call.path)
                        if p in ov.changes:
                            emit({"type": "change", **change_view(p, ov.changes[p])})
                    results.append(f"[{i}] {call.tool} {call.path or call.pattern}\n{text}")
                    steps_log.append({"tool": call.tool, "label": label, "ok": ok})
                if len(step.calls) > MAX_CALLS:
                    results.append(f"(only the first {MAX_CALLS} calls were run; send the rest in the next turn)")
                convo.append(("user", render_prompt("code_edit.results", results="\n\n".join(results))))
                record["changes"] = ov.changes
                await self._db.save_code_edit(_row(record))
            else:
                summary = "Reached the step limit. What is proposed so far is below; ask for the rest in a follow-up."
        finally:
            record["changes"] = ov.changes
            record["usage"]["steps"] = record["usage"].get("steps", 0) + len(steps_log)
            record["messages"].append({"role": "agent", "text": summary or "Done.", "steps": steps_log[-40:], "at": datetime.now(UTC).isoformat()})
            await self._db.save_code_edit(_row(record))
            self._audit.record(project_id=project_id, phase=phase, agent_role="CodeAssistant", event="code_edit.proposed", human_reviewer=user.email,
                               detail={"session": sid, "scope": scope, "targets": ov.targets[:20], "changed": sorted(ov.changes)[:30], "prompt": prompt[:300],
                                       "model": usage.get("model"), "steps": len(steps_log)})
        emit({"type": "done", "sessionId": sid, "summary": summary or "Done.", "changes": [change_view(p, c) for p, c in ov.changes.items()],
              "usage": {k: usage.get(k) for k in ("model", "provider", "promptTokens", "completionTokens")}})

    # ------------------------------------------------------------ review, apply, undo
    async def get(self, project_id: str, session_id: str, user: UserPublic) -> dict[str, Any]:
        s = await self._owned(project_id, session_id, user)
        return {"id": s["id"], "scope": s["scope"], "status": s["status"], "title": s["title"], "targets": s["targets"], "messages": s["messages"],
                "changes": [change_view(p, c) for p, c in s["changes"].items()], "applied": [change_view(p, c) for p, c in s["applied"].items()],
                "usage": s["usage"]}

    async def list(self, project_id: str, user: UserPublic, scope: str | None = None) -> list[dict]:
        await self._authz.assert_project_access(project_id, user)
        return [{"id": r["id"], "scope": r["scope"], "title": r["title"], "status": r["status"], "pending": int(r["pending"]), "applied": int(r["applied_count"]),
                 "turns": int(r["turns"]), "updatedAt": r["updated_at"].isoformat()} for r in await self._db.list_code_edits(project_id, user.id, scope)]

    async def _owned(self, project_id: str, session_id: str, user: UserPublic) -> dict:
        await self._authz.assert_project_access(project_id, user)
        s = await self._db.get_code_edit(project_id, session_id)
        if not s or s["user_id"] != user.id:
            raise SdlcError("NOT_FOUND", "Session not found")
        return s

    async def apply(self, project_id: str, session_id: str, user: UserPublic, paths: list[str] | None = None) -> dict[str, Any]:
        s = await self._owned(project_id, session_id, user)
        await self._authorise(project_id, s["scope"], user)
        pending = dict(s["changes"])
        chosen = {p: pending[p] for p in (paths if paths is not None else list(pending)) if p in pending}
        if not chosen:
            raise SdlcError("VALIDATION_FAILED", "There is nothing selected to apply")
        ws = self._workspace(project_id, s["scope"], s["phase"])
        await self._check_unchanged(ws, chosen)
        for p, c in chosen.items():
            await self._write(s, ws, p, c["action"], c["after"], user)
        applied = {**s["applied"], **chosen}
        rest = {p: c for p, c in pending.items() if p not in chosen}
        s.update(changes=rest, applied=applied, status="applied" if not rest else "proposed")
        await self._db.save_code_edit(s)
        self._audit.record(project_id=project_id, phase=s["phase"], agent_role="CodeAssistant", event="code_edit.applied", human_reviewer=user.email,
                           detail={"session": session_id, "scope": s["scope"], "files": sorted(chosen)[:40]})
        return {"applied": sorted(chosen), "remaining": sorted(rest), "status": s["status"]}

    async def _check_unchanged(self, ws: Workspace, chosen: dict[str, dict]) -> None:
        """Someone else may have edited a file since the assistant read it; do not overwrite their work silently."""
        for p, c in chosen.items():
            now = await ws.read(p)
            if c["action"] == "create":
                if now is not None:
                    raise SdlcError("GATE_CONFLICT", f"{p} now exists. Ask the assistant to try again.")
            elif now != c["before"]:
                raise SdlcError("GATE_CONFLICT", f"{p} was changed after the assistant read it. Discard this proposal and ask again.")

    async def revert(self, project_id: str, session_id: str, user: UserPublic) -> dict[str, Any]:
        s = await self._owned(project_id, session_id, user)
        await self._authorise(project_id, s["scope"], user)
        if not s["applied"]:
            raise SdlcError("VALIDATION_FAILED", "Nothing was applied in this session")
        ws = self._workspace(project_id, s["scope"], s["phase"])
        for p, c in s["applied"].items():
            if c["action"] == "create":
                await self._write(s, ws, p, "delete", None, user)
            elif c["action"] == "delete":
                await self._write(s, ws, p, "create", c["before"], user)
            else:
                await self._write(s, ws, p, "modify", c["before"], user)
        s.update(applied={}, status="reverted")
        await self._db.save_code_edit(s)
        self._audit.record(project_id=project_id, phase=s["phase"], agent_role="CodeAssistant", event="code_edit.reverted", human_reviewer=user.email,
                           detail={"session": session_id})
        return {"status": "reverted"}

    async def discard(self, project_id: str, session_id: str, user: UserPublic) -> dict[str, Any]:
        s = await self._owned(project_id, session_id, user)
        s.update(changes={}, status="discarded" if not s["applied"] else s["status"])
        await self._db.save_code_edit(s)
        return {"status": s["status"]}

    # ------------------------------------------------------------ writing to the project
    async def _write(self, s: dict, ws: Workspace, path: str, action: str, content: str | None, user: UserPublic) -> None:
        if s["scope"] == "uploaded":
            if action == "delete":
                await self._db.delete_codebase_file(s["project_id"], path)
                return
            await self._db.upsert_codebase_file(project_id=s["project_id"], path=path, content=content or "", uploaded_by=user.id)
            try:
                await self._rag.index_codebase_file(s["project_id"], path, content or "")
            except Exception:  # noqa: BLE001 - the copy is saved even when the search index lags
                log.warning("could not reindex %s", path, exc_info=True)
            return
        assert isinstance(ws, GeneratedWorkspace)
        phase = int(s["phase"])
        row = await ws.row(path)
        if action == "modify" and row is not None:
            if row.get("storage_key"):
                await self._content.put(row["storage_key"], content or "")
            await self._db.update_artefact_content(row["id"], (content or "") if not row.get("storage_key") else (content or "")[:2000])
        elif action == "create":
            from ..repos.pg import new_id
            aid = new_id()
            type_ = "UNIT_TESTS" if _is_test(path) else "APP_CODE"
            key = source_key(s["project_id"], phase, path)
            await self._content.put(key, content or "")
            await self._db.insert_artefact(project_id=s["project_id"], phase=phase, type_=type_, title=path, content=(content or "")[:2000], url=None,
                                           storage_key=key, storage_mode=self._content.mode, artefact_id=aid, lineage_id=aid, version=1)
            await self._plan_files(s["project_id"], phase, add=path)
        elif action == "delete" and row is not None:
            await self._db.supersede_artefact(row["id"])
            await self._plan_files(s["project_id"], phase, remove=path)

    async def _plan_files(self, project_id: str, phase: int, add: str | None = None, remove: str | None = None) -> None:
        """Keep the explorer's tree (built from the approved structure) in step with files the assistant adds or removes."""
        plan = await self._db.latest_code_plan(project_id, phase)
        if not plan:
            return
        st = dict(plan["structure"])
        files = [f for f in st.get("files", []) if f.get("path") != remove]
        if add and not any(f.get("path") == add for f in files):
            files.append({"path": add, "purpose": "Added with the code assistant", "kind": "test" if _is_test(add) else "source", "layer": ""})
        st["files"] = files
        await self._db.update_code_plan_structure(plan["id"], st)


def _running_label(c: ToolCall) -> str:
    return {"list_dir": f"Listing {c.path or 'the root'}", "read_file": f"Reading {c.path}", "search": f"Searching for {c.pattern[:40]}",
            "edit_file": f"Editing {c.path}", "write_file": f"Writing {c.path}", "delete_file": f"Deleting {c.path}",
            "check_syntax": f"Checking {c.path}"}[c.tool]


def _compact(convo: list[tuple[str, str]]) -> list[dict[str, str]]:
    """The conversation as messages. When it grows past the budget, older tool results are shortened (the latest are kept whole)."""
    total = sum(len(t) for _, t in convo)
    out: list[dict[str, str]] = []
    for i, (role, text) in enumerate(convo):
        recent = i >= len(convo) - 4 or i == 0
        if total > CONTEXT_BUDGET and not recent and role == "user":
            text = text[:600] + "\n… (older result shortened; read the file again if you need it)"
        out.append({"role": role, "content": text})
    return out


def _row(r: dict) -> dict:
    return {**r, "targets": r["targets"], "messages": r["messages"], "changes": r["changes"], "applied": r["applied"], "usage": r["usage"]}
