"""Deterministic rendering: canonical JSON (authoritative) + a markdown twin for people and
IDE assistants. Same input always yields byte-identical output, so hashes are meaningful."""

from __future__ import annotations

import hashlib
import json
import math
from typing import Any

from pydantic import BaseModel

from .schema import SCHEMA_VERSION, Charter, ForkRecord, ReleaseIndex, SprintDigest

BANNER = f"<!-- GENERATED BY DEVMIND (schema {SCHEMA_VERSION}) — DO NOT EDIT. Regenerated from project sources. -->"


def canonical_json(obj: BaseModel | dict[str, Any]) -> str:
    data = obj.model_dump(mode="json") if isinstance(obj, BaseModel) else obj
    return json.dumps(data, sort_keys=True, indent=2, ensure_ascii=False) + "\n"


def sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def est_tokens(text: str) -> int:
    """Deterministic token estimate (~4 chars/token). Good enough for budgeting; never calls a model."""
    return math.ceil(len(text) / 4)


def _bullets(items: list[str]) -> str:
    return "\n".join(f"- {i}" for i in items) if items else "- none"


def charter_md(c: Charter) -> str:
    return "\n".join([
        BANNER, f"# {c.name} — project charter", "",
        f"**Vision:** {c.vision}", f"**Stack:** {c.techStack}", "",
        "## Constraints", _bullets(c.constraints), "",
        "## Definition of Done", _bullets(c.definitionOfDone), "",
        "## Key decisions", _bullets(c.keyDecisions), "",
    ])


def sprint_md(d: SprintDigest) -> str:
    done = [f"{s.id} {s.title}" + (f" ({s.jiraKey})" if s.jiraKey else "") for s in d.stories if s.status == "done"]
    carried = [f"{s.id} {s.title}" for s in d.stories if s.status != "done"]
    return "\n".join([
        BANNER, f"# {d.id} — {d.goal}", f"Release: {d.release}", "",
        d.summary, "",
        "## Done", _bullets(done), "",
        "## Carried / dropped", _bullets(carried), "",
        "## Decisions", _bullets([f"{x.id} {x.title}: {x.rationale}" for x in d.decisions]), "",
        "## Open issues", _bullets(d.openIssues), "",
    ])


def release_md(r: ReleaseIndex) -> str:
    fork = [f"**Forked from:** {r.forkedFrom}" + (f" at {r.forkBaseline['sprint']}" if r.forkBaseline.get("sprint") else ""), ""] \
        if r.forkedFrom else []
    return "\n".join([
        BANNER, f"# {r.id} — {r.name}" + ("" if r.closed else " (open)"), "",
        f"**Goal:** {r.goal}", "", *fork, r.summary, "",
        "## Sprints", _bullets(r.sprints), "",
        "## Decisions", _bullets([f"{x.id} {x.title}: {x.rationale}" for x in r.decisions]), "",
        "## Living-spec pointers", _bullets([f"{k} → {v}" for k, v in sorted(r.specPointers.items())]), "",
        "## Open items", _bullets(r.openItems), "",
    ])


def readme_md() -> str:
    return "\n".join([
        BANNER, "# .devmind", "",
        "This folder is generated and maintained by DevMind. Do not edit these files by hand: changes are",
        "detected (hash mismatch) and overwritten from the project's sources.", "",
        "- `charter.*` project charter (always loaded)", "- `releases/*` one index per release",
        "- `sprints/*` sprint digests (recent)", "- `archive/*` older sprints rolled up per release",
        "- `lookup.json` id/keyword lookup so nothing scans folders", "- `manifest.json` file list, tiers and hashes", "",
    ])


def carried_md(f: ForkRecord) -> str:
    """The carried context as one readable document (also what the context packet loads, within a budget)."""
    by_state: dict[str, list[str]] = {"carried": [], "modified": [], "new": [], "retired": []}
    for c in f.carried:
        src = f" ← {c.carriedFrom.release}" if c.carriedFrom else ""
        head = f"[{c.kind}] {c.title}{src}"
        by_state.setdefault(c.state, []).append(head + (f"\n  {' '.join(c.text.split())[:500]}" if c.text else ""))
    out = [BANNER, f"# {f.release} — context carried from {f.forkedFrom or 'nowhere'}", ""]
    if f.baseline:
        out += [f"Baseline: {f.baseline.get('release', '')} {f.baseline.get('sprint', '')}".strip(), ""]
    for state, title in (("carried", "Carried as is"), ("modified", "Carried and modified in this release"),
                         ("new", "New in this release"), ("retired", "Retired")):
        out += [f"## {title}", _bullets(by_state[state]), ""]
    return "\n".join(out)
