/**
 * Professional mock corpus.
 *
 * The offline provider must demonstrate the platform's real quality bar, not
 * placeholder text: these builders emit consultancy-grade artifacts — an HLD
 * with C4 views, measurable NFRs, a STRIDE threat table and DR strategy; an
 * LLD with an error taxonomy, resilience settings and an RFC 7807 OpenAPI
 * contract; a test strategy with entry/exit criteria and a workload model; a
 * hardened CI/CD pipeline with SAST/SCA/SBOM gates; and layered production
 * code with real tests.
 *
 * Everything stays DETERMINISTIC (seeded from the request) so e2e suites keep
 * their guarantees, and the `BUG-MARKER` sentinel still drives the CI failure
 * path used by the build-recovery tests.
 */

/**
 * Deliberate defect seed appended to one phase-6 file. The simulated CI fails
 * while it is present, which is what makes the Build Recovery Loop observable
 * offline; the AI fix commit rewrites that file without this line.
 */
export const BUG_SEED =
  '// BUG-MARKER — deliberate defect seed so the Build Recovery Loop is demonstrable\n' +
  '// offline; the AI fix commit removes this line and CI turns green.';

/** The corrected file the fix persona commits: identical minus the seed. */
export function repairedFile(path: string): string {
  return [
    `// ${path} — corrected by the automated fix loop.`,
    '// The invalid type assignment flagged by CI (TS2322) has been removed;',
    '// behaviour is otherwise unchanged and covered by the existing tests.',
    '',
    'export {};',
  ].join('\n');
}

const svc = (topic: string) => topic.replace(/[^A-Za-z0-9]+/g, ' ').trim().split(' ').slice(0, 3).join(' ') || 'Platform Service';
const slug = (topic: string) => svc(topic).toLowerCase().replace(/\s+/g, '-');
/** A 2–6 letter uppercase Jira project key from the product name. */
const projKey = (topic: string) => {
  const initials = topic.replace(/[^A-Za-z0-9 ]+/g, '').trim().split(/\s+/).map((w) => w[0] ?? '').join('').toUpperCase();
  return (initials.length >= 2 ? initials : (svc(topic).replace(/[^A-Za-z]/g, '').toUpperCase() + 'PROJ')).slice(0, 5) || 'PROJ';
};

export function phase1(topic: string, seed: string): string {
  const name = svc(topic);
  return JSON.stringify({
    epics: [
      {
        title: `${name} — core capability`,
        businessCase:
          `Deliver ${topic} as a production service. Today the process is manual (spreadsheets + ` +
          `email), which cannot evidence controls and does not scale with forecast 3x volume growth. ` +
          `Automating it reduces manual handling effort by ~60% and cuts end-to-end processing from ` +
          `hours to minutes.`,
        successMetric:
          'Straight-through-processing rate — baseline 0%, target >= 95% by day 60 (metric `stp_ratio`).',
        targetQuarter: '2026-Q3',
        priority: 'High',
        features: [
          {
            title: 'Request intake & resilient processing',
            description:
              'Idempotent submission API with schema/business-rule validation, asynchronous ' +
              'at-least-once processing with exactly-once side effects, and operator-replayable ' +
              'failure handling.',
            priority: 'Highest',
            acceptanceCriteria: [
              'A request can be submitted, validated, processed and its status queried end to end.',
              'A transient downstream outage never produces duplicate side effects or lost requests.',
            ],
            stories: [
              {
                title: 'Idempotent request submission',
                statement: {
                  asA: 'operations analyst',
                  iWant: `to submit ${topic.toLowerCase()} requests through the API`,
                  soThat: 'processing starts immediately without manual re-keying',
                },
                acceptanceCriteria: [
                  'Given a valid request with all mandatory fields\nWhen POST /v1/requests is called with a unique Idempotency-Key\nThen a 201 Created is returned within 500ms (p99) with the resource id and Location header',
                  'Given a request that repeats a previously used Idempotency-Key with an identical body\nWhen POST /v1/requests is called\nThen the original 201 response is replayed and no duplicate record is created',
                  'Given a payload missing the mandatory reference field\nWhen POST /v1/requests is called\nThen a 400 problem+json is returned listing the field path, the violated rule and no stack trace',
                  'Given a caller whose token lacks the requests:write scope\nWhen POST /v1/requests is called\nThen a 403 problem+json is returned and the attempt is written to the audit log',
                ],
                storyPoints: 5,
                priority: 'Highest',
                estimationRationale:
                  'New endpoint plus idempotency store and validation; well-understood but touches auth and persistence.',
                subTasks: [
                  { title: 'Define request schema + validation rules', estimatedHours: 4 },
                  { title: 'Implement idempotency-key store (Redis SETNX, 24h TTL)', estimatedHours: 6 },
                  { title: 'Wire OAuth2 scope check + problem+json errors', estimatedHours: 4 },
                  { title: 'Contract + unit tests incl. replay and 4xx paths', estimatedHours: 5 },
                ],
              },
              {
                title: 'Retry-safe failure handling',
                statement: {
                  asA: 'service owner',
                  iWant: 'failed submissions to be retryable without duplication',
                  soThat: 'transient downstream outages do not create data-integrity issues',
                },
                acceptanceCriteria: [
                  'Given a downstream dependency times out after 3 attempts\nWhen the retry budget is exhausted\nThen the request is parked in the dead-letter queue with the failure reason and remains replayable',
                  'Given a parked request is replayed after the dependency recovers\nWhen processing succeeds\nThen exactly one downstream side effect exists and the original correlation id is preserved',
                ],
                storyPoints: 8,
                priority: 'High',
                estimationRationale:
                  'Exactly-once semantics across a queue + DLQ + replay is the highest-risk slice; needs careful integration testing.',
                subTasks: [
                  { title: 'Add retry-with-backoff + circuit breaker to the downstream client', estimatedHours: 6 },
                  { title: 'Implement DLQ parking + replay endpoint', estimatedHours: 8 },
                  { title: 'Idempotent side-effect guard keyed by correlation id', estimatedHours: 6 },
                  { title: 'Chaos/integration tests for outage + replay', estimatedHours: 6 },
                ],
              },
            ],
          },
          {
            title: 'Audit & compliance evidence',
            description:
              'An immutable, queryable audit trail for every state change, with scoped export for ' +
              'compliance officers.',
            priority: 'High',
            acceptanceCriteria: [
              'Every state change is evidenced with a tamper-evident audit record.',
              'Compliance officers can export audit data filtered to their authorised scope.',
            ],
            stories: [
              {
                title: 'Immutable audit trail',
                statement: {
                  asA: 'compliance officer',
                  iWant: 'an immutable audit record for every state change',
                  soThat: 'I can evidence controls during an audit',
                },
                acceptanceCriteria: [
                  'Given any state-changing operation\nWhen it completes successfully or fails\nThen an audit event is persisted with actor, action, resource id, before/after status, correlation id and UTC timestamp',
                  'Given an attempt to modify an existing audit record\nWhen the update is issued\nThen it is rejected and the attempt is itself audited',
                  'Given an audit query for a date range\nWhen a compliance officer requests an export\nThen results are returned paginated and filtered to their authorised scope only',
                ],
                storyPoints: 3,
                priority: 'High',
                estimationRationale:
                  'Append-only store and export query; low algorithmic risk, some access-control nuance.',
                subTasks: [
                  { title: 'Append-only audit table with WORM semantics', estimatedHours: 5 },
                  { title: 'Scoped, paginated export endpoint', estimatedHours: 4 },
                  { title: 'Tests for immutability + scope filtering', estimatedHours: 3 },
                ],
              },
            ],
          },
        ],
      },
    ],
    definitionOfReady: [
      'Story follows as-a/I-want/so-that and is INVEST-compliant',
      'Acceptance criteria are written in Gherkin with at least one negative scenario',
      'Estimated in story points with a rationale and decomposed into sub-tasks',
      'Dependencies identified and non-functional expectations noted',
    ],
    definitionOfDone: [
      'Code reviewed and merged behind a feature flag',
      'Acceptance criteria demonstrated and automated tests green in CI',
      'Observability (metrics, logs, traces) and audit events emitted',
      'Docs/runbook updated; PRD acceptance criteria satisfied',
    ],
    jiraProjectKey: projKey(topic),
    prdMarkdown: [
      `# Product Requirements Document — ${name}`,
      '',
      '| Field | Value |',
      '|---|---|',
      '| Status | Draft for review |',
      '| Author | Product Owner (AI-assisted) |',
      `| Revision | ${seed} |`,
      '',
      '## 1. Problem statement',
      `Today ${topic.toLowerCase()} is handled through spreadsheets and email, averaging 4.5 hours of`,
      'analyst effort per batch with a 6% rework rate from transcription errors. The manual path',
      'cannot meet the regulatory requirement to evidence every state change, and volume is',
      'forecast to grow 3x over the next 18 months.',
      '',
      '## 2. Objectives and success metrics',
      '| Objective | Metric | Baseline | Target | Measured by |',
      '|---|---|---|---|---|',
      '| Remove manual handling | Straight-through-processing rate | 0% | >= 95% | Service metric `stp_ratio` |',
      '| Reduce cycle time | p95 end-to-end processing | 4.5 h | < 5 min | Trace span duration |',
      '| Eliminate rework | Correction events per 1k requests | 60 | < 5 | Audit query |',
      '| Evidence controls | Audit completeness | partial | 100% of state changes | Quarterly control test |',
      '',
      '## 3. Scope',
      '**In scope:** request submission API, validation, processing workflow, audit trail, operator',
      'exception queue, reporting export.',
      '',
      '**Out of scope (explicitly):** bulk historical migration (handled by a separate one-off job),',
      'mobile client, multi-region active/active (deferred until volume exceeds 500 rps).',
      '',
      '## 4. Personas',
      '| Persona | Goal | Frequency | Key constraint |',
      '|---|---|---|---|',
      '| Operations analyst | Submit and track requests | Hourly | Cannot re-key data |',
      '| Operations lead | Resolve exceptions | Daily | Needs full failure context |',
      '| Compliance officer | Evidence controls | Quarterly | Immutable, exportable trail |',
      '| Service owner | Keep the service healthy | Continuous | Actionable alerts only |',
      '',
      '## 5. Functional requirements',
      '- FR-1 Submit a request with idempotent semantics and receive a durable identifier.',
      '- FR-2 Validate against the published schema and business rules, returning field-level errors.',
      '- FR-3 Process asynchronously with at-least-once delivery and exactly-once side effects.',
      '- FR-4 Expose request status and history to authorised callers.',
      '- FR-5 Route unrecoverable failures to an operator exception queue with replay.',
      '- FR-6 Emit an immutable audit event for every state transition.',
      '',
      '## 6. Non-functional requirements',
      '| ID | Attribute | Target |',
      '|---|---|---|',
      '| NFR-1 | Availability | 99.9% monthly (43.2 min error budget) |',
      '| NFR-2 | Latency | p95 < 300 ms, p99 < 500 ms for synchronous submission |',
      '| NFR-3 | Throughput | 200 rps sustained, 500 rps peak for 10 min |',
      '| NFR-4 | Durability | RPO 5 min, RTO 30 min |',
      '| NFR-5 | Retention | Operational data 13 months; audit records 7 years |',
      '| NFR-6 | Security | OAuth2 client-credentials, TLS 1.2+, AES-256 at rest |',
      '| NFR-7 | Accessibility | Operator console meets WCAG 2.2 AA |',
      '',
      '## 7. Dependencies and assumptions',
      '- Identity provider issues scoped tokens (`requests:read`, `requests:write`, `audit:read`).',
      '- Downstream ledger exposes a synchronous API with a published 99.5% SLA.',
      '- Assumption: peak volume stays below 500 rps for the first 12 months; revisit if breached.',
      '',
      '## 8. Risks',
      '| Risk | Likelihood | Impact | Mitigation | Owner |',
      '|---|---|---|---|---|',
      '| Downstream ledger instability | Medium | High | Retry with backoff, DLQ, circuit breaker | Service owner |',
      '| Volume growth beyond forecast | Medium | Medium | Autoscaling + quarterly capacity review | Platform |',
      '| Audit retention cost | Low | Medium | Lifecycle to cold storage after 13 months | FinOps |',
      '',
      '## 9. Rollout and measurement',
      'Ship behind the `' + slug(topic) + '-enabled` flag. Pilot with one operations team for two',
      'weeks, compare STP rate and cycle time against baseline, then progressively enable by team.',
      'Rollback = disable the flag; the manual path remains available throughout the pilot.',
      '',
      '## 10. Open questions',
      '| # | Question | Owner | Needed by |',
      '|---|---|---|---|',
      '| 1 | Is the 7-year audit retention contractual or regulatory? | Compliance | Before phase 2 sign-off |',
      '| 2 | Who approves exception replays above £50k value? | Ops lead | Before go-live |',
    ].join('\n'),
  });
}

export function phase2(topic: string, seed: string): string {
  const name = svc(topic);
  const id = slug(topic);
  return JSON.stringify({
    hldNarrative: [
      `# High-Level Design — ${name}`,
      '',
      `**Status:** For architecture review · **Revision:** ${seed}`,
      '',
      '## 1. Executive summary',
      `${name} replaces a manual, spreadsheet-driven process with an event-driven service on AWS.`,
      'Synchronous submission is served by a containerised API behind an Application Load Balancer;',
      'processing is decoupled through a queue so downstream outages degrade throughput rather than',
      'availability. The design targets 99.9% availability, p99 < 500 ms submission latency and',
      'RPO 5 min / RTO 30 min, at an estimated steady-state cost of ~$1,850/month.',
      '',
      '## 2. Business context and drivers',
      '- Regulatory: every state change must be evidenced for 7 years.',
      '- Commercial: 3x volume growth forecast over 18 months without headcount growth.',
      '- Operational: current 6% rework rate is the largest source of customer complaints.',
      '',
      '## 3. Scope and non-goals',
      '**In scope:** submission API, validation, async processing, audit store, exception queue, reporting export.',
      '**Non-goals:** multi-region active/active; real-time streaming analytics; replacing the ledger.',
      '',
      '## 4. Assumptions and constraints',
      '| # | Statement | Type | Impact if wrong |',
      '|---|---|---|---|',
      '| A1 | Peak load stays under 500 rps for 12 months | Assumption | Re-evaluate sharding |',
      '| A2 | Ledger API sustains 99.5% availability | Assumption | Error budget consumed by dependency |',
      '| C1 | Must deploy into the existing shared VPC | Constraint | No public subnets available |',
      '| C2 | Data must remain in eu-west-2 | Constraint | Rules out us-east-1 managed services |',
      '',
      '## 5. Architecture — C4 context',
      'Actors: Operations analyst, Operations lead, Compliance officer, and the upstream Scheduler.',
      `External systems: Identity Provider (OIDC), Core Ledger (REST), Notification Service (SMTP relay).`,
      '',
      '## 6. Architecture — container view',
      '| Container | Technology | Responsibility | Scaling |',
      '|---|---|---|---|',
      '| API service | Containerised web service on ECS Fargate | Auth, validation, idempotency, enqueue | 2–20 tasks on CPU 60% |',
      '| Processor | Worker on ECS Fargate | Consume queue, call ledger, persist outcome | 2–30 tasks on queue depth |',
      '| Primary datastore | Aurora PostgreSQL (Multi-AZ) | Requests, outcomes, exception queue | Writer + 1 reader |',
      '| Cache | ElastiCache Redis | Idempotency keys, hot lookups | 2 nodes, cluster mode off |',
      '| Queue | SQS (standard) + DLQ | Decouple submission from processing | Managed |',
      '| Audit store | S3 with Object Lock (compliance mode) | Immutable 7-year audit trail | Managed |',
      '',
      '## 7. Interface catalogue',
      '| Interface | Direction | Protocol | Sync/Async | SLA | Failure handling |',
      '|---|---|---|---|---|---|',
      '| `POST /v1/requests` | Inbound | HTTPS/JSON | Sync | p99 500 ms | 4xx validation, 503 on shed |',
      '| `GET /v1/requests/{id}` | Inbound | HTTPS/JSON | Sync | p99 200 ms | 404 problem+json |',
      '| Ledger `POST /postings` | Outbound | HTTPS/JSON | Sync | 2 s timeout | 3 retries, backoff+jitter, breaker |',
      '| Notification | Outbound | SMTP | Async | best effort | Fire-and-forget, logged |',
      '',
      '## 8. Data architecture',
      '| Dataset | Classification | Store | Encryption | Retention |',
      '|---|---|---|---|---|',
      '| Request payloads | Internal | Aurora | KMS CMK at rest, TLS in transit | 13 months |',
      '| Counterparty identifiers | Confidential (PII) | Aurora, column-level masked in non-prod | KMS CMK | 13 months |',
      '| Audit events | Confidential | S3 Object Lock | KMS CMK | 7 years |',
      '',
      '## 9. Security architecture',
      'AuthN: OAuth2 client-credentials via the corporate IdP; JWT validated against JWKS with 5-minute',
      'clock skew. AuthZ: scope-based at the edge, row-level ownership checks in the service layer.',
      'Secrets are held in Secrets Manager and injected by task role — never baked into images.',
      '',
      '### Threat model (STRIDE)',
      '| Threat | Vector | Mitigation |',
      '|---|---|---|',
      '| Spoofing | Forged caller identity | JWKS signature validation, short token TTL, mTLS to ledger |',
      '| Tampering | Altered payload in flight | TLS 1.2+, request signing on ledger calls |',
      '| Repudiation | Denial of an action | Immutable S3 Object Lock audit trail with actor + correlation id |',
      '| Information disclosure | Over-broad query results | Scope + ownership filters, column masking in non-prod, no PII in logs |',
      '| Denial of service | Submission flood | WAF rate limiting, per-client quotas, load shedding with 503 + Retry-After |',
      '| Elevation of privilege | Scope escalation | Least-privilege IAM, deny-by-default policies, quarterly access review |',
      '',
      '## 10. Quality attributes',
      '| Attribute | Target | Verification |',
      '|---|---|---|',
      '| Availability | 99.9% monthly | Synthetic probe + SLO burn-rate alert |',
      '| Latency | p95 300 ms / p99 500 ms | k6 load test in CI, dashboard percentiles |',
      '| Throughput | 200 rps sustained / 500 rps peak | Quarterly load test |',
      '| RPO / RTO | 5 min / 30 min | Semi-annual DR game day |',
      '| Scalability | Linear to 500 rps | Load test at 1x, 2x, 2.5x |',
      '',
      '## 11. Capacity and cost',
      'Sizing at 200 rps sustained: API 6 tasks (0.5 vCPU / 1 GB), processor 8 tasks, Aurora db.r6g.large',
      'writer + reader, Redis cache.t4g.medium x2. Estimated steady state ~$1,850/month; peak-day',
      'autoscaling adds ~$180. Reviewed quarterly against actual utilisation.',
      '',
      '## 12. Deployment topology',
      'Three environments (dev, staging, production) in separate accounts. Private subnets only;',
      'egress via NAT. Blue/green deployment with automated health verification and 10-minute bake.',
      '',
      '## 13. Resilience and failure modes',
      '| Failure | Detection | Behaviour | Recovery |',
      '|---|---|---|---|',
      '| Ledger unavailable | Breaker opens after 5 failures in 30 s | Queue depth grows, submissions still accepted | Auto half-open probe every 30 s |',
      '| Database failover | Health check + connection errors | Writes fail fast, retried from queue | Aurora Multi-AZ failover < 60 s |',
      '| Queue poison message | Redrive after 5 receives | Message to DLQ with reason | Operator replay after fix |',
      '| AZ loss | ALB health checks | Traffic shifts to healthy AZs | Autoscaling replaces capacity |',
      '',
      '## 14. Disaster recovery',
      'Automated Aurora backups with 5-minute PITR; cross-region snapshot copy daily. Runbook-driven',
      'restore into the DR account targets RTO 30 min. DR exercised semi-annually with documented results.',
      '',
      '## 15. Migration and cutover',
      'Dual-run for two weeks: manual process remains authoritative while the service shadows it and',
      'differences are reported daily. Cut over per operations team behind the feature flag. Rollback',
      'is a flag flip; no schema changes are destructive during the dual-run window.',
      '',
      '## 16. Risks',
      '| Risk | Impact | Likelihood | Mitigation | Owner |',
      '|---|---|---|---|---|',
      '| Ledger latency exceeds 2 s under load | High | Medium | Breaker + async fallback, agreed SLA | Service owner |',
      '| PII leakage through logs | High | Low | Structured logging allow-list + output guardrail | Security |',
      '| Cost overrun from audit retention | Medium | Medium | S3 lifecycle to Glacier after 13 months | FinOps |',
      '',
      '## 17. Traceability',
      '| Requirement | Realised by |',
      '|---|---|',
      '| FR-1 Idempotent submission | API service + Redis idempotency store |',
      '| FR-3 Exactly-once side effects | SQS + idempotency key on ledger posting |',
      '| FR-6 Immutable audit | S3 Object Lock audit store |',
      '| NFR-1 Availability 99.9% | Multi-AZ, autoscaling, breaker, DLQ |',
      '| NFR-4 RPO/RTO | PITR + cross-region snapshots |',
    ].join('\n'),
    mermaidArchitecture: [
      'flowchart LR',
      '  subgraph Clients',
      '    analyst([Operations Analyst])',
      '    sched([Scheduler])',
      '  end',
      '  subgraph AWS["AWS eu-west-2 — private subnets"]',
      '    waf[WAF + ALB]',
      '    api[API Service<br/>ECS Fargate]',
      '    q[[SQS + DLQ]]',
      '    proc[Processor<br/>ECS Fargate]',
      '    db[(Aurora PostgreSQL<br/>Multi-AZ)]',
      '    cache[(ElastiCache Redis<br/>idempotency)]',
      '    audit[(S3 Object Lock<br/>audit 7y)]',
      '  end',
      '  idp{{Identity Provider}}',
      '  ledger{{Core Ledger API}}',
      '  analyst --> waf',
      '  sched --> waf',
      '  waf --> api',
      '  api -- validate token --> idp',
      '  api --> cache',
      '  api --> db',
      '  api --> q',
      '  q --> proc',
      '  proc -- retry + breaker --> ledger',
      '  proc --> db',
      '  api --> audit',
      '  proc --> audit',
    ].join('\n'),
    structurizrDsl: [
      `workspace "${name}" "Generated by the AI-SDLC platform" {`,
      '  model {',
      '    analyst = person "Operations Analyst" "Submits and tracks requests"',
      '    compliance = person "Compliance Officer" "Evidences controls"',
      '    idp = softwareSystem "Identity Provider" "OIDC token issuance" "External"',
      '    ledger = softwareSystem "Core Ledger" "System of record for postings" "External"',
      `    system = softwareSystem "${name}" {`,
      '      api = container "API Service" "Auth, validation, idempotency" "ECS Fargate"',
      '      processor = container "Processor" "Async processing and ledger posting" "ECS Fargate"',
      '      db = container "Primary Datastore" "Requests and outcomes" "Aurora PostgreSQL" "Database"',
      '      cache = container "Idempotency Cache" "Replay protection" "ElastiCache Redis" "Database"',
      '      queue = container "Work Queue" "Decoupling and retry" "SQS"',
      '      auditStore = container "Audit Store" "Immutable trail" "S3 Object Lock" "Database"',
      '    }',
      '    analyst -> api "Submits requests" "HTTPS/JSON"',
      '    compliance -> api "Exports audit" "HTTPS/JSON"',
      '    api -> idp "Validates tokens" "OIDC/JWKS"',
      '    api -> cache "Reserves idempotency key"',
      '    api -> db "Persists request"',
      '    api -> queue "Enqueues work"',
      '    queue -> processor "Delivers work"',
      '    processor -> ledger "Posts entries" "HTTPS/JSON, mTLS"',
      '    processor -> db "Records outcome"',
      '    api -> auditStore "Writes audit event"',
      '    processor -> auditStore "Writes audit event"',
      '  }',
      '  views {',
      '    systemContext system "Context" { include * autolayout lr }',
      '    container system "Containers" { include * autolayout lr }',
      '    theme default',
      '  }',
      '}',
    ].join('\n'),
    architecturePrinciples: [
      'Stateless services behind the load balancer — scale horizontally, no session affinity.',
      'Fail closed on authorisation; fail open only on non-security, best-effort paths.',
      'Every state change is evented and audited; the audit store is write-once.',
      'Design for the downstream being unavailable — decouple with a queue and idempotent retries.',
      'Prefer managed services over self-managed to minimise operational surface.',
    ],
    components: [
      { name: 'API Service', responsibility: 'Validate, authorise and accept submissions; expose status',
        technology: 'ECS Fargate (containerised)', dependsOn: ['Redis', 'Aurora', 'SQS'] },
      { name: 'Processor', responsibility: 'Consume work items and post to the ledger idempotently',
        technology: 'ECS Fargate worker', dependsOn: ['SQS', 'Core Ledger', 'Aurora'] },
      { name: 'Aurora PostgreSQL', responsibility: 'System of record for requests and state',
        technology: 'Aurora PostgreSQL Multi-AZ', dependsOn: [] },
      { name: 'Audit Store', responsibility: 'Immutable, tamper-evident audit of every state change',
        technology: 'S3 Object Lock (compliance mode)', dependsOn: [] },
    ],
    designPatterns: [
      { name: 'Idempotent Receiver', appliedTo: 'Submission API + ledger posting',
        rationale: 'Guarantees exactly-once side effects under retries and duplicate delivery.' },
      { name: 'Circuit Breaker + Retry with backoff', appliedTo: 'Downstream ledger client',
        rationale: 'Prevents cascading failure and gives the dependency time to recover.' },
      { name: 'Transactional Outbox', appliedTo: 'Request persistence + queue publish',
        rationale: 'Atomic write-and-publish so no work item is lost or double-emitted.' },
      { name: 'Dead-Letter Queue', appliedTo: 'Unprocessable work items',
        rationale: 'Isolates poison messages and makes them operator-replayable.' },
    ],
    qualityAttributes: [
      { id: 'NFR-1', attribute: 'Availability', target: '99.9% monthly',
        tactic: 'Multi-AZ, health checks, queue-decoupled downstream' },
      { id: 'NFR-2', attribute: 'Latency', target: 'p99 < 500 ms (submission)',
        tactic: 'Synchronous path does only validate + persist + enqueue' },
      { id: 'NFR-3', attribute: 'Durability', target: 'RPO 5 min / RTO 30 min',
        tactic: 'Aurora PITR + Multi-AZ failover' },
      { id: 'NFR-4', attribute: 'Security', target: 'OAuth2, TLS 1.2+, AES-256 at rest',
        tactic: 'Scoped tokens, KMS-managed keys, least-privilege IAM' },
    ],
    deploymentArchitecture: {
      title: `${name} — AWS deployment`,
      direction: 'TB',
      clusters: [
        { id: 'vpc', label: 'VPC 10.0.0.0/16', parent: '' },
        { id: 'az_a', label: 'AZ eu-west-2a', parent: 'vpc' },
        { id: 'az_b', label: 'AZ eu-west-2b', parent: 'vpc' },
        { id: 'pub_a', label: 'public-subnet-a', parent: 'az_a' },
        { id: 'priv_a', label: 'private-subnet-a', parent: 'az_a' },
        { id: 'priv_b', label: 'private-subnet-b', parent: 'az_b' },
      ],
      nodes: [
        { id: 'user', label: 'Customer', service: 'users', group: '' },
        { id: 'cf', label: 'CloudFront', service: 'cloudfront', group: '' },
        { id: 'waf', label: 'WAF', service: 'waf', group: '' },
        { id: 'alb', label: 'Application LB', service: 'alb', group: 'pub_a' },
        { id: 'nat', label: 'NAT Gateway', service: 'nat', group: 'pub_a' },
        { id: 'api', label: 'API Service (Fargate)', service: 'fargate', group: 'priv_a' },
        { id: 'proc', label: 'Processor (Fargate)', service: 'fargate', group: 'priv_b' },
        { id: 'sqs', label: 'SQS + DLQ', service: 'sqs', group: 'priv_a' },
        { id: 'db', label: 'Aurora Multi-AZ', service: 'aurora', group: 'priv_a' },
        { id: 'cache', label: 'ElastiCache', service: 'elasticache', group: 'priv_a' },
        { id: 'audit', label: 'S3 Object Lock (audit)', service: 's3', group: '' },
      ],
      edges: [
        { fromId: 'user', toId: 'cf', label: 'HTTPS' },
        { fromId: 'cf', toId: 'waf', label: '' },
        { fromId: 'waf', toId: 'alb', label: '' },
        { fromId: 'alb', toId: 'api', label: 'route' },
        { fromId: 'api', toId: 'cache', label: 'idempotency' },
        { fromId: 'api', toId: 'db', label: 'write' },
        { fromId: 'api', toId: 'sqs', label: 'enqueue' },
        { fromId: 'sqs', toId: 'proc', label: 'consume' },
        { fromId: 'proc', toId: 'db', label: 'update' },
        { fromId: 'api', toId: 'audit', label: 'audit event' },
      ],
    },
    adrs: [
      {
        title: 'ADR-001: Queue-decoupled processing rather than synchronous ledger calls',
        status: 'Accepted',
        context:
          'Submission must stay available (99.9%) while the downstream ledger publishes only a 99.5% SLA. ' +
          'A synchronous design would inherit the weaker dependency SLA and couple submission latency to it.',
        optionsConsidered: [
          'Synchronous call to the ledger inside the request — rejected: submission availability becomes min(ours, ledger) and p99 is hostage to ledger latency.',
          'Queue-decoupled processing with idempotent posting — chosen.',
          'Event streaming (Kafka) — rejected for v1: no existing platform, operational cost unjustified below 500 rps.',
        ],
        decision:
          'Accept and persist the request, enqueue work on SQS, and post to the ledger from a processor ' +
          'with bounded retries, exponential backoff with jitter and a circuit breaker; failures land in a DLQ.',
        consequences:
          'Positive: submission availability is independent of the ledger; load spikes absorb into queue depth. ' +
          'Negative: eventual consistency requires a status endpoint and an operator exception queue; ' +
          'exactly-once side effects must be enforced with an idempotency key on the posting call.',
      },
      {
        title: 'ADR-002: Aurora PostgreSQL as the system of record',
        status: 'Accepted',
        context:
          'The domain is strongly relational with strict integrity requirements, while parts of the payload ' +
          'are schema-flexible. The team has deep PostgreSQL operational experience.',
        optionsConsidered: [
          'DynamoDB — rejected: multi-item transactional integrity and ad-hoc compliance queries are awkward and costly.',
          'Self-managed PostgreSQL on EC2 — rejected: patching, failover and backup burden without offsetting benefit.',
          'Aurora PostgreSQL Multi-AZ — chosen.',
        ],
        decision:
          'Aurora PostgreSQL Multi-AZ with RDS Proxy for connection pooling, JSONB for flexible payload ' +
          'attributes, and PITR enabled with a 5-minute recovery point.',
        consequences:
          'Positive: transactional integrity, familiar tooling, managed failover under 60 s, PITR meets RPO. ' +
          'Negative: vertical scaling ceiling accepted for v1; a sharding decision is deferred until sustained load exceeds 500 rps.',
      },
      {
        title: 'ADR-003: Immutable audit in S3 Object Lock rather than an application table',
        status: 'Accepted',
        context:
          'Audit records must be tamper-evident and retained for 7 years, well beyond operational data retention.',
        optionsConsidered: [
          'Append-only database table — rejected: a privileged operator can still mutate rows; retention inflates the operational database.',
          'S3 with Object Lock in compliance mode — chosen.',
          'Third-party audit SaaS — rejected: data residency requirement and additional vendor risk.',
        ],
        decision:
          'Write audit events as immutable objects to S3 with Object Lock (compliance mode, 7-year retention), ' +
          'lifecycle-transitioned to Glacier after 13 months.',
        consequences:
          'Positive: tamper-evidence satisfies the control objective; storage cost is an order of magnitude lower. ' +
          'Negative: queries need Athena rather than SQL joins; an export endpoint must be provided for compliance users.',
      },
    ],
  });
}

export function phase3(topic: string, seed: string): string {
  const name = svc(topic);
  const id = slug(topic);
  return JSON.stringify({
    lldMarkdown: [
      `# Low-Level Design — ${name}`,
      '',
      `**Implements:** HLD rev ${seed} · **Audience:** implementing engineers`,
      '',
      '## 1. Component decomposition',
      '| Component | Single responsibility | Depends on |',
      '|---|---|---|',
      '| `RequestController` | HTTP binding, auth enforcement, response shaping | `RequestService` |',
      '| `RequestService` | Business rules, idempotency, orchestration | `RequestRepository`, `QueuePublisher`, `AuditWriter` |',
      '| `RequestRepository` | Persistence and query construction | Datastore |',
      '| `LedgerClient` | Outbound posting with resilience policies | Ledger API |',
      '| `ExceptionHandler` | Failure classification and DLQ routing | `AuditWriter` |',
      '',
      'Dependencies point inward only: controllers depend on the application layer, which depends on',
      'domain abstractions; infrastructure implements those abstractions. No framework annotations',
      'appear in domain types.',
      '',
      '## 2. Primary flow',
      'Submission: authorise → validate → reserve idempotency key (SETNX, 24 h TTL) → persist request',
      '(status `ACCEPTED`) → publish to queue → write audit event → return 201 with Location.',
      '',
      '## 3. Failure flow',
      'If the idempotency key already exists with a matching payload hash, the stored response is',
      'replayed with `Idempotent-Replay: true`. If the payload differs, 409 is returned. If persistence',
      'succeeds but publishing fails, the transactional outbox row remains unsent and the relay',
      'republishes within 30 s — the request is never lost.',
      '',
      '## 4. Transaction and concurrency model',
      '- Isolation: READ COMMITTED; the outbox insert shares the request transaction.',
      '- Optimistic concurrency on status transitions via a `version` column; conflicts return 409.',
      '- Idempotency keys are reserved before work begins and released only on terminal outcomes.',
      '- Processor consumers are idempotent: the ledger posting carries the request id as its key.',
      '',
      '## 5. Error taxonomy',
      '| Domain error | HTTP | `type` | Client message | Retryable |',
      '|---|---|---|---|---|',
      '| `ValidationFailed` | 400 | `/errors/validation` | Field-level violations | No |',
      '| `Unauthenticated` | 401 | `/errors/unauthenticated` | Token missing or invalid | No |',
      '| `ScopeDenied` | 403 | `/errors/forbidden` | Insufficient scope | No |',
      '| `RequestNotFound` | 404 | `/errors/not-found` | Unknown request id | No |',
      '| `IdempotencyConflict` | 409 | `/errors/conflict` | Key reused with a different payload | No |',
      '| `RateLimited` | 429 | `/errors/rate-limited` | Retry after the given interval | Yes |',
      '| `DependencyUnavailable` | 503 | `/errors/dependency` | Temporarily unable to process | Yes |',
      '',
      'All errors are RFC 7807 problem+json carrying `correlationId`; stack traces are never exposed.',
      '',
      '## 6. Resilience settings',
      '| Dependency | Connect | Read | Retries | Backoff | Breaker |',
      '|---|---|---|---|---|---|',
      '| Ledger API | 500 ms | 2 s | 3 | 200 ms base, x2, ±20% jitter, cap 4 s | 5 failures / 30 s → open 30 s |',
      '| Datastore | 250 ms | 3 s | 1 (transient only) | 100 ms | — |',
      '| Cache | 100 ms | 250 ms | 0 (fail open) | — | — |',
      '',
      'Cache failure degrades to database-backed idempotency rather than rejecting traffic.',
      '',
      '## 7. Caching',
      '| Key | Contents | TTL | Invalidation |',
      '|---|---|---|---|',
      '| `idem:{key}` | Request id + payload hash + stored response | 24 h | Natural expiry |',
      '| `ref:{code}` | Reference data lookup | 15 min | Publish event on change |',
      '',
      '## 8. API conventions',
      'Pagination is cursor-based (`?cursor=&limit=`, default 50, max 200) returning `nextCursor`.',
      'Sorting is restricted to an allow-list. Versioning is by URI major version; a version is',
      'supported for 12 months after its successor ships, with `Deprecation` and `Sunset` headers.',
      '',
      '## 9. Observability plan',
      '| Signal | Name | Purpose |',
      '|---|---|---|',
      '| Metric | `requests_submitted_total{outcome}` | Volume and error ratio |',
      '| Metric | `request_submit_duration_seconds` (histogram) | Latency SLO |',
      '| Metric | `ledger_posting_failures_total{reason}` | Dependency health |',
      '| Metric | `queue_depth` / `dlq_depth` | Backlog and poison detection |',
      '| Log field | `correlationId`, `requestId`, `actor`, `outcome`, `durationMs` | Structured troubleshooting |',
      '| Trace span | `submit`, `persist`, `enqueue`, `ledger.post` | End-to-end latency attribution |',
      '',
      'Alerts: SLO burn rate > 2% of budget/hour (page), `dlq_depth` > 0 for 15 min (ticket),',
      'breaker open > 5 min (page).',
      '',
      '## 10. Configuration inventory',
      '| Key | Default | Source |',
      '|---|---|---|',
      '| `LEDGER_BASE_URL` | — | Environment |',
      '| `LEDGER_TIMEOUT_MS` | 2000 | Environment |',
      '| `IDEMPOTENCY_TTL_HOURS` | 24 | Environment |',
      `| \`FEATURE_${id.toUpperCase().replace(/-/g, '_')}_ENABLED\` | false | Feature flag service |`,
      '| Database credentials | — | Secrets Manager via task role |',
    ].join('\n'),
    components: [
      { name: 'SubmissionController', responsibility: 'HTTP boundary: bind, validate, delegate; no business logic',
        collaborators: ['RequestService', 'IdempotencyStore'] },
      { name: 'RequestService', responsibility: 'Orchestrate persistence + outbox publish in one transaction',
        collaborators: ['RequestRepository', 'OutboxPublisher'] },
      { name: 'LedgerClient', responsibility: 'Post to the ledger with retry, timeout and circuit breaker',
        collaborators: ['CircuitBreaker'] },
      { name: 'ProcessorWorker', responsibility: 'Consume the queue and drive exactly-once posting',
        collaborators: ['LedgerClient', 'RequestRepository', 'DeadLetterQueue'] },
    ],
    errorTaxonomy: [
      { code: 'ERR_VALIDATION', httpStatus: 400, message: 'Request failed schema/business validation', retryable: false },
      { code: 'ERR_UNAUTHENTICATED', httpStatus: 401, message: 'Missing or invalid token', retryable: false },
      { code: 'ERR_FORBIDDEN', httpStatus: 403, message: 'Token lacks the required scope', retryable: false },
      { code: 'ERR_IDEMPOTENCY_CONFLICT', httpStatus: 409, message: 'Idempotency-Key reused with a different body', retryable: false },
      { code: 'ERR_DEPENDENCY_UNAVAILABLE', httpStatus: 503, message: 'Downstream ledger unavailable; retry later', retryable: true },
    ],
    resilience: { retries: 3, timeoutMs: 2000, circuitBreaker: '5 failures / 30s window, half-open after 15s', cacheTtlSeconds: 300 },
    componentDiagram: {
      title: `${name} — component & deployment detail`,
      direction: 'LR',
      clusters: [
        { id: 'task', label: 'ECS Task (Fargate)', parent: '' },
        { id: 'data', label: 'Data stores', parent: '' },
      ],
      nodes: [
        { id: 'ctrl', label: 'SubmissionController', service: 'container', group: 'task' },
        { id: 'svc', label: 'RequestService', service: 'component', group: 'task' },
        { id: 'ledger', label: 'LedgerClient (breaker)', service: 'component', group: 'task' },
        { id: 'cache', label: 'Redis (idempotency)', service: 'cache', group: 'data' },
        { id: 'db', label: 'Aurora', service: 'aurora', group: 'data' },
        { id: 'sqs', label: 'SQS + DLQ', service: 'sqs', group: 'data' },
        { id: 'core', label: 'Core Ledger API', service: 'api', group: '' },
      ],
      edges: [
        { fromId: 'ctrl', toId: 'svc', label: 'validate' },
        { fromId: 'svc', toId: 'cache', label: 'SETNX' },
        { fromId: 'svc', toId: 'db', label: 'tx + outbox' },
        { fromId: 'svc', toId: 'sqs', label: 'publish' },
        { fromId: 'ledger', toId: 'core', label: 'POST /postings' },
        { fromId: 'sqs', toId: 'ledger', label: 'process' },
      ],
    },
    mermaidSequence: [
      'sequenceDiagram',
      '  autonumber',
      '  participant C as Client',
      '  participant A as API Service',
      '  participant R as Redis (idempotency)',
      '  participant D as Aurora',
      '  participant Q as SQS',
      '  participant P as Processor',
      '  participant L as Core Ledger',
      '  C->>A: POST /v1/requests (Idempotency-Key)',
      '  A->>A: validate token scope + payload',
      '  A->>R: SETNX idem:{key} (TTL 24h)',
      '  alt key already reserved',
      '    R-->>A: exists',
      '    A-->>C: 201 replay (Idempotent-Replay: true)',
      '  else new request',
      '    R-->>A: reserved',
      // No ';' in sequence message text — mermaid treats it as a statement
      // separator and the diagram fails to parse.
      '    A->>D: BEGIN, INSERT request + outbox, COMMIT',
      '    A->>Q: publish work item',
      '    A-->>C: 201 Created + Location',
      '    Q->>P: deliver work item',
      '    P->>L: POST /postings (idempotency key)',
      '    alt ledger unavailable',
      '      L-->>P: 5xx / timeout',
      '      P->>P: retry x3 with backoff+jitter, then open breaker',
      '      P->>Q: message to DLQ with reason',
      '    else posted',
      '      L-->>P: 201 posting id',
      '      P->>D: UPDATE request SET status=COMPLETED',
      '    end',
      '  end',
    ].join('\n'),
    plantumlDiagrams: [
      [
        '@startuml',
        `title ${name} — component structure`,
        'skinparam componentStyle rectangle',
        'package "API layer" {',
        '  [RequestController]',
        '}',
        'package "Application layer" {',
        '  [RequestService]',
        '  [ExceptionHandler]',
        '}',
        'package "Domain" {',
        '  [Request]',
        '  [IdempotencyKey]',
        '}',
        'package "Infrastructure" {',
        '  [RequestRepository]',
        '  [QueuePublisher]',
        '  [LedgerClient]',
        '  [AuditWriter]',
        '}',
        '[RequestController] --> [RequestService]',
        '[RequestService] --> [Request]',
        '[RequestService] --> [RequestRepository]',
        '[RequestService] --> [QueuePublisher]',
        '[RequestService] --> [AuditWriter]',
        '[ExceptionHandler] --> [AuditWriter]',
        '[LedgerClient] ..> [Request]',
        '@enduml',
      ].join('\n'),
    ],
    openapiYaml: [
      'openapi: 3.0.3',
      'info:',
      `  title: ${name} API`,
      '  version: 1.0.0',
      `  description: |`,
      `    Submission and tracking API for ${topic}.`,
      '    All errors follow RFC 7807 (application/problem+json) and carry a correlationId.',
      '  contact:',
      '    name: Service Owner',
      '    email: service-owner@example.com',
      'servers:',
      '  - url: https://api.example.com',
      '    description: Production',
      'security:',
      '  - oauth2: [requests:read]',
      'tags:',
      '  - name: Requests',
      '    description: Submission and status',
      'paths:',
      '  /v1/requests:',
      '    post:',
      '      operationId: createRequest',
      '      tags: [Requests]',
      '      summary: Submit a request',
      '      description: Idempotent submission. Reusing an Idempotency-Key replays the original response.',
      '      security:',
      '        - oauth2: [requests:write]',
      '      parameters:',
      '        - name: Idempotency-Key',
      '          in: header',
      '          required: true',
      '          schema: { type: string, format: uuid }',
      '      requestBody:',
      '        required: true',
      '        content:',
      '          application/json:',
      '            schema: { $ref: "#/components/schemas/RequestCreate" }',
      '            example:',
      '              reference: REQ-2026-0001',
      '              amount: 1250.00',
      '              currency: GBP',
      '      responses:',
      '        "201":',
      '          description: Created',
      '          headers:',
      '            Location:',
      '              schema: { type: string }',
      '          content:',
      '            application/json:',
      '              schema: { $ref: "#/components/schemas/Request" }',
      '        "400": { $ref: "#/components/responses/Problem" }',
      '        "401": { $ref: "#/components/responses/Problem" }',
      '        "403": { $ref: "#/components/responses/Problem" }',
      '        "409": { $ref: "#/components/responses/Problem" }',
      '        "429": { $ref: "#/components/responses/Problem" }',
      '        "503": { $ref: "#/components/responses/Problem" }',
      '    get:',
      '      operationId: listRequests',
      '      tags: [Requests]',
      '      summary: List requests',
      '      parameters:',
      '        - name: cursor',
      '          in: query',
      '          schema: { type: string }',
      '        - name: limit',
      '          in: query',
      '          schema: { type: integer, minimum: 1, maximum: 200, default: 50 }',
      '        - name: status',
      '          in: query',
      '          schema: { type: string, enum: [ACCEPTED, COMPLETED, FAILED] }',
      '      responses:',
      '        "200":',
      '          description: OK',
      '          content:',
      '            application/json:',
      '              schema: { $ref: "#/components/schemas/RequestPage" }',
      '        "401": { $ref: "#/components/responses/Problem" }',
      '        "403": { $ref: "#/components/responses/Problem" }',
      '  /v1/requests/{requestId}:',
      '    get:',
      '      operationId: getRequest',
      '      tags: [Requests]',
      '      summary: Retrieve a request',
      '      parameters:',
      '        - name: requestId',
      '          in: path',
      '          required: true',
      '          schema: { type: string, format: uuid }',
      '      responses:',
      '        "200":',
      '          description: OK',
      '          content:',
      '            application/json:',
      '              schema: { $ref: "#/components/schemas/Request" }',
      '        "404": { $ref: "#/components/responses/Problem" }',
      'components:',
      '  securitySchemes:',
      '    oauth2:',
      '      type: oauth2',
      '      flows:',
      '        clientCredentials:',
      '          tokenUrl: https://idp.example.com/oauth2/token',
      '          scopes:',
      '            requests:read: Read requests',
      '            requests:write: Submit requests',
      '  responses:',
      '    Problem:',
      '      description: Error (RFC 7807)',
      '      content:',
      '        application/problem+json:',
      '          schema: { $ref: "#/components/schemas/Problem" }',
      '  schemas:',
      '    RequestCreate:',
      '      type: object',
      '      required: [reference, amount, currency]',
      '      additionalProperties: false',
      '      properties:',
      '        reference: { type: string, minLength: 1, maxLength: 64 }',
      '        amount: { type: number, format: double, minimum: 0.01 }',
      '        currency: { type: string, pattern: "^[A-Z]{3}$" }',
      '    Request:',
      '      type: object',
      '      required: [id, reference, status, createdAt]',
      '      properties:',
      '        id: { type: string, format: uuid }',
      '        reference: { type: string }',
      '        status: { type: string, enum: [ACCEPTED, COMPLETED, FAILED] }',
      '        createdAt: { type: string, format: date-time }',
      '    RequestPage:',
      '      type: object',
      '      required: [items]',
      '      properties:',
      '        items:',
      '          type: array',
      '          items: { $ref: "#/components/schemas/Request" }',
      '        nextCursor: { type: string, nullable: true }',
      '    Problem:',
      '      type: object',
      '      required: [type, title, status]',
      '      properties:',
      '        type: { type: string, format: uri }',
      '        title: { type: string }',
      '        status: { type: integer }',
      '        detail: { type: string }',
      '        correlationId: { type: string }',
      '        errors:',
      '          type: array',
      '          items:',
      '            type: object',
      '            properties:',
      '              field: { type: string }',
      '              rule: { type: string }',
    ].join('\n'),
    dbmlSchema: [
      `// ${name} — physical model. Access patterns drive every index below.`,
      'Table requests {',
      '  id uuid [pk, note: "Server-generated identifier"]',
      '  reference varchar(64) [not null, unique, note: "Client business reference"]',
      '  idempotency_key uuid [not null, unique]',
      '  payload_hash char(64) [not null, note: "SHA-256 of the canonical payload"]',
      '  amount numeric(18,2) [not null]',
      '  currency char(3) [not null]',
      "  status varchar(16) [not null, default: 'ACCEPTED', note: 'ACCEPTED|COMPLETED|FAILED']",
      '  version integer [not null, default: 1, note: "Optimistic concurrency"]',
      '  created_at timestamptz [not null, default: `now()`]',
      '  updated_at timestamptz [not null, default: `now()`]',
      '',
      '  indexes {',
      '    (status, created_at) [name: "idx_requests_status_created", note: "Operator queue listing"]',
      '    (created_at) [name: "idx_requests_created", note: "Reporting export by date range"]',
      '  }',
      '}',
      '',
      'Table request_events {',
      '  id uuid [pk]',
      '  request_id uuid [not null, ref: > requests.id]',
      '  event varchar(32) [not null]',
      '  detail jsonb',
      '  correlation_id uuid [not null]',
      '  occurred_at timestamptz [not null, default: `now()`]',
      '',
      '  indexes {',
      '    (request_id, occurred_at) [name: "idx_events_request_time"]',
      '  }',
      '}',
      '',
      'Table outbox {',
      '  id uuid [pk]',
      '  request_id uuid [not null, ref: > requests.id]',
      '  payload jsonb [not null]',
      '  published_at timestamptz [note: "NULL until the relay publishes"]',
      '  attempts integer [not null, default: 0]',
      '',
      '  indexes {',
      '    (published_at) [name: "idx_outbox_unpublished", note: "Partial scan for the relay"]',
      '  }',
      '}',
    ].join('\n'),
    cdkStack: [
      "import { Duration, RemovalPolicy, Stack, type StackProps, Tags } from 'aws-cdk-lib';",
      "import { InstanceClass, InstanceSize, InstanceType, Port, SecurityGroup, SubnetType, Vpc } from 'aws-cdk-lib/aws-ec2';",
      "import { Cluster, ContainerImage, FargateService, FargateTaskDefinition, LogDrivers } from 'aws-cdk-lib/aws-ecs';",
      "import { AuroraPostgresEngineVersion, ClusterInstance, Credentials, DatabaseCluster, DatabaseClusterEngine } from 'aws-cdk-lib/aws-rds';",
      "import { Queue, QueueEncryption } from 'aws-cdk-lib/aws-sqs';",
      "import { Key } from 'aws-cdk-lib/aws-kms';",
      "import { RetentionDays } from 'aws-cdk-lib/aws-logs';",
      "import type { Construct } from 'constructs';",
      '',
      'export interface ServiceStackProps extends StackProps {',
      "  readonly environment: 'dev' | 'staging' | 'prod';",
      '}',
      '',
      '/**',
      ` * ${name} runtime. Private networking, customer-managed encryption keys,`,
      ' * least-privilege task roles and a dead-letter queue on every consumer.',
      ' */',
      'export class ServiceStack extends Stack {',
      '  constructor(scope: Construct, id: string, props: ServiceStackProps) {',
      '    super(scope, id, props);',
      '',
      "    Tags.of(this).add('Application', '" + name + "');",
      "    Tags.of(this).add('Environment', props.environment);",
      "    Tags.of(this).add('ManagedBy', 'cdk');",
      '',
      "    const key = new Key(this, 'DataKey', {",
      '      enableKeyRotation: true,',
      "      description: '" + name + " data encryption key',",
      "      removalPolicy: props.environment === 'prod' ? RemovalPolicy.RETAIN : RemovalPolicy.DESTROY,",
      '    });',
      '',
      "    const vpc = new Vpc(this, 'Vpc', {",
      '      maxAzs: 3,',
      '      natGateways: props.environment === "prod" ? 3 : 1,',
      '      subnetConfiguration: [',
      "        { name: 'private', subnetType: SubnetType.PRIVATE_WITH_EGRESS, cidrMask: 24 },",
      "        { name: 'isolated', subnetType: SubnetType.PRIVATE_ISOLATED, cidrMask: 24 },",
      '      ],',
      '    });',
      '',
      "    const dlq = new Queue(this, 'WorkDlq', {",
      '      encryption: QueueEncryption.KMS,',
      '      encryptionMasterKey: key,',
      '      retentionPeriod: Duration.days(14),',
      '    });',
      '',
      "    const workQueue = new Queue(this, 'WorkQueue', {",
      '      encryption: QueueEncryption.KMS,',
      '      encryptionMasterKey: key,',
      '      visibilityTimeout: Duration.seconds(60),',
      '      deadLetterQueue: { queue: dlq, maxReceiveCount: 5 },',
      '    });',
      '',
      "    const database = new DatabaseCluster(this, 'Database', {",
      '      engine: DatabaseClusterEngine.auroraPostgres({ version: AuroraPostgresEngineVersion.VER_16_4 }),',
      "      writer: ClusterInstance.provisioned('writer', {",
      '        instanceType: InstanceType.of(InstanceClass.R6G, InstanceSize.LARGE),',
      '      }),',
      "      readers: [ClusterInstance.provisioned('reader', {",
      '        instanceType: InstanceType.of(InstanceClass.R6G, InstanceSize.LARGE),',
      '      })],',
      '      vpc,',
      '      vpcSubnets: { subnetType: SubnetType.PRIVATE_ISOLATED },',
      '      storageEncryptionKey: key,',
      '      backup: { retention: Duration.days(35) },',
      '      deletionProtection: props.environment === "prod",',
      '      cloudwatchLogsExports: ["postgresql"],',
      '      cloudwatchLogsRetention: RetentionDays.ONE_MONTH,',
      '    });',
      '',
      "    const cluster = new Cluster(this, 'Cluster', { vpc, containerInsights: true });",
      '',
      "    const taskDefinition = new FargateTaskDefinition(this, 'ApiTask', {",
      '      cpu: 512,',
      '      memoryLimitMiB: 1024,',
      '    });',
      '',
      "    taskDefinition.addContainer('api', {",
      "      image: ContainerImage.fromRegistry('REGISTRY/" + id + ":latest'),",
      "      logging: LogDrivers.awsLogs({ streamPrefix: 'api', logRetention: RetentionDays.ONE_MONTH }),",
      '      environment: { NODE_ENV: props.environment, QUEUE_URL: workQueue.queueUrl },',
      '      portMappings: [{ containerPort: 8080 }],',
      '      healthCheck: {',
      "        command: ['CMD-SHELL', 'curl -fsS http://localhost:8080/healthz || exit 1'],",
      '        interval: Duration.seconds(30),',
      '        retries: 3,',
      '        startPeriod: Duration.seconds(15),',
      '      },',
      '    });',
      '',
      "    const serviceSg = new SecurityGroup(this, 'ServiceSg', { vpc, allowAllOutbound: true });",
      "    const service = new FargateService(this, 'ApiService', {",
      '      cluster,',
      '      taskDefinition,',
      '      desiredCount: props.environment === "prod" ? 6 : 2,',
      '      securityGroups: [serviceSg],',
      '      vpcSubnets: { subnetType: SubnetType.PRIVATE_WITH_EGRESS },',
      '      circuitBreaker: { rollback: true },',
      '    });',
      '',
      "    service.autoScaleTaskCount({ minCapacity: 2, maxCapacity: 20 }).scaleOnCpuUtilization('CpuScaling', {",
      '      targetUtilizationPercent: 60,',
      '      scaleInCooldown: Duration.minutes(5),',
      '      scaleOutCooldown: Duration.minutes(1),',
      '    });',
      '',
      '    // Least privilege: the task may only consume the work queue and read its own secret.',
      '    workQueue.grantConsumeMessages(taskDefinition.taskRole);',
      '    database.connections.allowDefaultPortFrom(serviceSg, "API service to database");',
      '  }',
      '}',
    ].join('\n'),
  });
}

export function phase4(topic: string, seed: string): string {
  const name = svc(topic);
  return JSON.stringify({
    testStrategyMarkdown: [
      `# Test Strategy — ${name}`,
      '',
      `**Revision:** ${seed} · **Owner:** QA Lead · **Applies to:** release 1.0`,
      '',
      '## 1. Objectives and scope',
      'Verify the functional requirements FR-1..FR-6 and demonstrate the NFR targets agreed in the HLD',
      '(99.9% availability, p95 300 ms / p99 500 ms, 200 rps sustained). Out of scope: the ledger’s own',
      'correctness (covered by its owning team) and historical migration.',
      '',
      '## 2. Test levels',
      '| Level | Responsibility | Tooling | Gate |',
      '|---|---|---|---|',
      '| Unit | Engineers | Native test runner | >= 80% line, >= 70% branch on changed code |',
      '| Contract | Engineers | OpenAPI schema validation | Contract diff must be additive |',
      '| Integration | Engineers + QA | Ephemeral environment | All critical paths green |',
      '| API/E2E | QA | Postman/newman, REST Assured | 100% of P1 cases pass |',
      '| UI | QA | Playwright (headless, 3 browsers) | 100% of P1 journeys pass |',
      '| Performance | QA + Platform | k6, JMeter, Locust | NFR thresholds met |',
      '| Security | Security | ZAP baseline, Trivy, SAST | No High/Critical open |',
      '| Accessibility | QA | axe on operator console | No WCAG 2.2 AA violations |',
      '',
      '## 3. Risk-based prioritisation',
      '| Risk area | Likelihood | Impact | Priority | Coverage emphasis |',
      '|---|---|---|---|---|',
      '| Duplicate side effects on retry | Medium | High | P1 | Idempotency replay + concurrent submit |',
      '| Ledger outage handling | Medium | High | P1 | Breaker, DLQ, replay |',
      '| Authorisation bypass | Low | High | P1 | Scope and ownership matrix |',
      '| Audit completeness | Low | High | P1 | Every state transition asserted |',
      '| Pagination correctness | Medium | Low | P3 | Boundary cases |',
      '',
      '## 4. Entry and exit criteria',
      '**Entry:** contract published and linted; ephemeral environment provisioned; seeded reference',
      'data available; unit suite green on the candidate build.',
      '',
      '**Exit:** 100% of P1 and >= 95% of P2 cases pass; zero open Critical/High defects; performance',
      'thresholds met at 1x and 2x load; security scans clean; RTM shows no uncovered requirement.',
      '',
      '## 5. Environments and test data',
      'Ephemeral per-PR environments provisioned from the same IaC as production. Test data is',
      'synthetic and generated per run; production data is never copied. Any PII-shaped fields use',
      'reserved fictitious ranges. Data is reset before each suite to guarantee independence.',
      '',
      '## 6. Defect management',
      '| Severity | Definition | Triage SLA | Fix SLA |',
      '|---|---|---|---|',
      '| Critical | Data loss, security breach, total outage | 1 h | 24 h |',
      '| High | Core journey blocked, no workaround | 4 h | 3 days |',
      '| Medium | Workaround exists | 1 day | Next sprint |',
      '| Low | Cosmetic or documentation | 3 days | Backlog |',
      '',
      '## 7. Automation and CI integration',
      'Unit and contract tests run on every push; API, UI and security suites run on every PR against',
      'an ephemeral environment; performance runs nightly and before release. Failures block the',
      'pipeline. Flaky tests are quarantined within 24 h and fixed or deleted within a week.',
      '',
      '## 8. Regression policy',
      'Every defect fix ships with the test that would have caught it. The P1 suite is the regression',
      'gate for all releases and must complete in under 15 minutes.',
    ].join('\n'),
    xrayTests: [
      {
        title: 'Submission is idempotent when the same key is replayed',
        priority: 'High',
        tracesTo: 'FR-1',
        preconditions: 'Valid client token with requests:write; no request exists for the chosen Idempotency-Key.',
        steps: [
          { action: 'POST /v1/requests with reference REQ-1001, amount 1250.00, currency GBP and Idempotency-Key K1', expectedResult: '201 Created; response body contains a UUID id; Location header set; p99 under 500 ms' },
          { action: 'Repeat the identical POST with Idempotency-Key K1', expectedResult: '201 with the SAME id, header Idempotent-Replay: true, and no second row in the requests table' },
          { action: 'POST with Idempotency-Key K1 but amount 9999.00', expectedResult: '409 problem+json type /errors/conflict; original record unchanged' },
        ],
      },
      {
        title: 'Validation rejects malformed payloads with field-level detail',
        priority: 'High',
        tracesTo: 'FR-2',
        preconditions: 'Valid client token with requests:write.',
        steps: [
          { action: 'POST /v1/requests omitting the reference field', expectedResult: '400 application/problem+json listing field "reference" and rule "required"; correlationId present; no stack trace' },
          { action: 'POST with currency "GBPX"', expectedResult: '400 citing field "currency" and the pattern rule' },
          { action: 'POST with amount 0', expectedResult: '400 citing field "amount" and the minimum rule' },
        ],
      },
      {
        title: 'Authorisation is enforced by scope and ownership',
        priority: 'High',
        tracesTo: 'NFR-6',
        preconditions: 'Two clients: A holds requests:write, B holds requests:read only.',
        steps: [
          { action: 'As client B, POST /v1/requests', expectedResult: '403 problem+json type /errors/forbidden; attempt recorded in the audit trail' },
          { action: 'As client B, GET a request created by client A', expectedResult: '404 (not 403) so existence is not disclosed' },
          { action: 'Call POST /v1/requests with no Authorization header', expectedResult: '401 problem+json' },
        ],
      },
      {
        title: 'Ledger outage parks work without data loss',
        priority: 'High',
        tracesTo: 'FR-5',
        preconditions: 'Ledger stub configured to return 503 for all calls.',
        steps: [
          { action: 'Submit 10 requests', expectedResult: 'All return 201; queue depth rises; no 5xx surfaced to the client' },
          { action: 'Wait for the retry budget to exhaust (3 attempts, backoff capped at 4 s)', expectedResult: 'Messages land in the DLQ with a failure reason; circuit breaker reports open; alert fires' },
          { action: 'Restore the ledger stub and replay the DLQ', expectedResult: 'All 10 complete exactly once; ledger shows 10 postings, not 20; original correlation ids preserved' },
        ],
      },
      {
        title: 'Every state transition produces an immutable audit record',
        priority: 'High',
        tracesTo: 'FR-6',
        preconditions: 'Audit store reachable; compliance token with audit:read.',
        steps: [
          { action: 'Submit a request and let it complete', expectedResult: 'Audit events exist for ACCEPTED and COMPLETED with actor, resource id, before/after status and UTC timestamp' },
          { action: 'Attempt to overwrite an audit object', expectedResult: 'Rejected by Object Lock; the attempt itself is audited' },
          { action: 'Export audit for the last 24 hours as the compliance user', expectedResult: 'Paginated export scoped to authorised records only' },
        ],
      },
    ],
    k6Script: [
      "import http from 'k6/http';",
      "import { check, sleep } from 'k6';",
      "import { Rate, Trend } from 'k6/metrics';",
      "import { uuidv4 } from 'https://jslib.k6.io/k6-utils/1.4.0/index.js';",
      '',
      '// Workload model derived from the HLD NFRs: 200 rps sustained, 500 rps peak for 10 min.',
      "const submitLatency = new Trend('submit_latency', true);",
      "const businessErrors = new Rate('business_errors');",
      '',
      'export const options = {',
      '  scenarios: {',
      '    steady_state: {',
      "      executor: 'ramping-arrival-rate',",
      '      startRate: 20,',
      "      timeUnit: '1s',",
      '      preAllocatedVUs: 100,',
      '      maxVUs: 400,',
      '      stages: [',
      "        { target: 200, duration: '3m' },   // ramp to sustained load",
      "        { target: 200, duration: '10m' },  // hold",
      "        { target: 500, duration: '2m' },   // peak burst",
      "        { target: 500, duration: '10m' },  // hold peak",
      "        { target: 0, duration: '2m' },     // ramp down",
      '      ],',
      '    },',
      '  },',
      '  thresholds: {',
      '    // Assert the agreed NFR targets, not arbitrary numbers.',
      "    'http_req_duration{scenario:steady_state}': ['p(95)<300', 'p(99)<500'],",
      "    'http_req_failed': ['rate<0.001'],",
      "    'business_errors': ['rate<0.01'],",
      '  },',
      '};',
      '',
      "const BASE = __ENV.BASE_URL || 'https://staging.example.com';",
      "const TOKEN = __ENV.ACCESS_TOKEN || 'placeholder-token';",
      '',
      'export default function () {',
      '  const payload = JSON.stringify({',
      '    reference: `REQ-${__VU}-${__ITER}`,',
      '    amount: Math.round((Math.random() * 5000 + 1) * 100) / 100,',
      "    currency: 'GBP',",
      '  });',
      '',
      '  const res = http.post(`${BASE}/v1/requests`, payload, {',
      '    headers: {',
      "      'Content-Type': 'application/json',",
      "      'Authorization': `Bearer ${TOKEN}`,",
      "      'Idempotency-Key': uuidv4(),",
      '    },',
      "    tags: { name: 'POST /v1/requests' },",
      '  });',
      '',
      '  submitLatency.add(res.timings.duration);',
      '  const ok = check(res, {',
      "    'status is 201': (r) => r.status === 201,",
      "    'body carries an id': (r) => typeof r.json('id') === 'string',",
      '  });',
      '  businessErrors.add(!ok);',
      '',
      '  sleep(Math.random() * 0.5 + 0.2); // think time 200-700ms',
      '}',
    ].join('\n'),
    postmanCollection: JSON.stringify({
      info: { name: `${name} API suite`, schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json' },
      item: [
        { name: 'Submit request — happy path (201)' },
        { name: 'Submit request — idempotent replay (201 same id)' },
        { name: 'Submit request — key reuse with different body (409)' },
        { name: 'Submit request — missing reference (400 problem+json)' },
        { name: 'Submit request — insufficient scope (403)' },
        { name: 'Get request — not found (404)' },
        { name: 'List requests — cursor pagination boundary' },
      ],
    }),
    rtmMarkdown: [
      '# Requirements Traceability Matrix',
      '',
      '| Requirement | Description | Design | Tests | Status |',
      '|---|---|---|---|---|',
      '| FR-1 | Idempotent submission | LLD §2, §4 | Idempotent replay; k6 steady state | ✅ Covered |',
      '| FR-2 | Schema and rule validation | LLD §5 | Validation rejects malformed payloads | ✅ Covered |',
      '| FR-3 | Exactly-once side effects | HLD ADR-001 | Ledger outage parks work | ✅ Covered |',
      '| FR-4 | Status and history exposure | OpenAPI GET endpoints | List/Get suites | ✅ Covered |',
      '| FR-5 | Exception queue and replay | LLD §3 | Ledger outage parks work | ✅ Covered |',
      '| FR-6 | Immutable audit | HLD ADR-003 | Audit record test | ✅ Covered |',
      '| NFR-2 | p95 300 ms / p99 500 ms | HLD §10 | k6 thresholds | ✅ Covered |',
      '| NFR-3 | 200 rps sustained / 500 peak | HLD §10 | k6 workload model | ✅ Covered |',
      '| NFR-6 | AuthN/AuthZ controls | HLD §9 | Authorisation matrix | ✅ Covered |',
      '| NFR-4 | RPO 5 min / RTO 30 min | HLD §14 | DR game day (manual, semi-annual) | ⚠️ Manual verification |',
      '',
      '**Gap analysis:** NFR-4 cannot be asserted in CI; it is verified by the documented DR exercise.',
      'No requirement is without coverage.',
    ].join('\n'),
    testLevels: [
      { level: 'unit', scope: 'Domain logic and validators in isolation', coverageTarget: '85% lines / 75% branches', tools: ['JUnit', 'Vitest'] },
      { level: 'integration', scope: 'API + persistence + queue with test containers', coverageTarget: 'all endpoints', tools: ['Testcontainers', 'REST Assured'] },
      { level: 'contract', scope: 'OpenAPI request/response conformance', coverageTarget: '100% of operations', tools: ['Postman/newman'] },
      { level: 'e2e', scope: 'Critical user journeys through the UI', coverageTarget: 'top 5 journeys', tools: ['Playwright'] },
      { level: 'performance', scope: 'Submission path at target load', coverageTarget: 'p95/p99 NFRs', tools: ['k6', 'JMeter', 'Locust'] },
      { level: 'security', scope: 'OWASP baseline + dependency and image scans', coverageTarget: 'no High/Critical', tools: ['ZAP', 'Snyk', 'Trivy'] },
    ],
    riskAreas: [
      { area: 'Idempotency under concurrent retries', likelihood: 'Medium', impact: 'High', priority: 'High', mitigation: 'Dedicated concurrency + replay tests; DLQ assertions' },
      { area: 'Ledger outage handling', likelihood: 'Medium', impact: 'High', priority: 'High', mitigation: 'Fault-injection integration tests for timeout/breaker/DLQ' },
      { area: 'AuthZ scope enforcement', likelihood: 'Low', impact: 'High', priority: 'High', mitigation: 'Authorisation matrix tests per role/scope' },
      { area: 'Performance regression', likelihood: 'Medium', impact: 'Medium', priority: 'Medium', mitigation: 'k6 thresholds gate the pipeline' },
    ],
    entryCriteria: [
      'Phase 3 LLD and OpenAPI approved and stable',
      'Test environment provisioned with masked, representative data',
      'CI can run the full suite on every PR',
    ],
    exitCriteria: [
      'All planned test levels executed; no open Critical/Major defects',
      'Coverage targets met; k6 thresholds green at target load',
      'RTM shows every requirement covered or an accepted, documented gap',
    ],
    defectSlas: [
      { severity: 'Critical', triage: '1 hour', resolution: '24 hours' },
      { severity: 'Major', triage: '4 hours', resolution: '3 business days' },
      { severity: 'Minor', triage: '2 business days', resolution: 'next release' },
    ],
  });
}

export function phase5(topic: string, seed: string): string {
  const name = svc(topic);
  const id = slug(topic);
  return JSON.stringify({
    workflowYaml: [
      `name: ${id}-ci`,
      '',
      'on:',
      '  push:',
      '    branches: [main]',
      '  pull_request:',
      '',
      'permissions:',
      '  contents: read',
      '  id-token: write        # OIDC federation — no long-lived AWS keys',
      '  security-events: write',
      '',
      'concurrency:',
      '  group: ${{ github.workflow }}-${{ github.ref }}',
      '  cancel-in-progress: true',
      '',
      'env:',
      '  REGISTRY: ghcr.io',
      `  IMAGE_NAME: \${{ github.repository }}/${id}`,
      '',
      'jobs:',
      '  checkout-and-setup:',
      '    name: Lint',
      '    runs-on: ubuntu-latest',
      '    steps:',
      '      - uses: actions/checkout@v4',
      '        with: { fetch-depth: 0 }',
      '      - uses: actions/setup-node@v4',
      "        with: { node-version: '22', cache: 'npm' }",
      '      - run: npm ci --prefer-offline',
      '      - name: lint',
      '        run: npm run lint -- --max-warnings=0',
      '',
      '  test:',
      '    name: Build and test',
      '    runs-on: ubuntu-latest',
      '    needs: checkout-and-setup',
      '    steps:',
      '      - uses: actions/checkout@v4',
      '      - uses: actions/setup-node@v4',
      "        with: { node-version: '22', cache: 'npm' }",
      '      - run: npm ci --prefer-offline',
      '      - name: build',
      '        run: npm run build',
      '      - name: unit and integration tests',
      '        run: npm test -- --coverage',
      '      - name: enforce coverage threshold',
      '        run: npx nyc check-coverage --lines 80 --branches 70',
      '      - uses: actions/upload-artifact@v4',
      '        if: always()',
      '        with: { name: test-results, path: reports/ }',
      '',
      '  snyk:',
      '    name: SCA and SAST',
      '    runs-on: ubuntu-latest',
      '    needs: checkout-and-setup',
      '    steps:',
      '      - uses: actions/checkout@v4',
      '      - name: dependency scan (SCA)',
      '        run: npx snyk test --severity-threshold=high',
      '        env: { SNYK_TOKEN: "${{ secrets.SNYK_TOKEN }}" }',
      '      - name: static analysis (SAST)',
      '        uses: github/codeql-action/analyze@v3',
      '      - name: infrastructure-as-code scan',
      '        run: npx checkov -d infra --quiet --compact',
      '',
      '  inspector:',
      '    name: Image scan and SBOM',
      '    runs-on: ubuntu-latest',
      '    needs: test',
      '    steps:',
      '      - uses: actions/checkout@v4',
      '      - name: build image',
      '        run: docker build -t "$IMAGE_NAME:${{ github.sha }}" .',
      '      - name: vulnerability scan (blocks on HIGH/CRITICAL)',
      '        uses: aquasecurity/trivy-action@master',
      '        with:',
      '          image-ref: "${{ env.IMAGE_NAME }}:${{ github.sha }}"',
      "          severity: 'CRITICAL,HIGH'",
      "          exit-code: '1'",
      '      - name: generate SBOM',
      '        run: npx @cyclonedx/cyclonedx-npm --output-file sbom.json',
      '      - name: sign the image',
      '        run: cosign sign --yes "$IMAGE_NAME:${{ github.sha }}"',
      '      - uses: actions/upload-artifact@v4',
      '        with: { name: sbom, path: sbom.json }',
      '',
      '  deploy:',
      '    name: Deploy',
      '    runs-on: ubuntu-latest',
      '    needs: [test, snyk, inspector]',
      "    if: github.ref == 'refs/heads/main'",
      '    environment:',
      '      name: production          # requires manual approval',
      '      url: https://api.example.com',
      '    steps:',
      '      - uses: actions/checkout@v4',
      '      - name: assume deployment role via OIDC',
      '        uses: aws-actions/configure-aws-credentials@v4',
      '        with:',
      '          role-to-assume: "${{ secrets.AWS_DEPLOY_ROLE_ARN }}"',
      '          aws-region: eu-west-2',
      '      - name: blue/green deploy',
      '        run: ./scripts/deploy.sh --strategy blue-green --bake 10m',
      '      - name: post-deploy verification',
      '        run: ./scripts/smoke.sh --url https://api.example.com --fail-fast',
      '      - name: rollback on failure',
      '        if: failure()',
      '        run: ./scripts/deploy.sh --rollback',
    ].join('\n'),
    dockerfiles: [
      {
        path: 'Dockerfile',
        content: [
          '# syntax=docker/dockerfile:1.7',
          '# ---- build stage -------------------------------------------------------',
          'FROM node:22.11.0-bookworm-slim AS build',
          'WORKDIR /app',
          'ENV NODE_ENV=production',
          '',
          '# Dependencies first so the layer caches independently of source changes.',
          'COPY package.json package-lock.json ./',
          'RUN --mount=type=cache,target=/root/.npm npm ci --include=dev',
          '',
          'COPY . .',
          'RUN npm run build && npm prune --omit=dev',
          '',
          '# ---- runtime stage -----------------------------------------------------',
          'FROM node:22.11.0-bookworm-slim AS runtime',
          'ENV NODE_ENV=production \\',
          '    NODE_OPTIONS="--enable-source-maps" \\',
          '    PORT=8080',
          '',
          '# Non-root runtime user; no build toolchain in this layer.',
          'RUN groupadd --gid 10001 app && useradd --uid 10001 --gid app --home /home/app --create-home app',
          'WORKDIR /app',
          '',
          'COPY --from=build --chown=app:app /app/node_modules ./node_modules',
          'COPY --from=build --chown=app:app /app/dist ./dist',
          'COPY --from=build --chown=app:app /app/package.json ./package.json',
          '',
          'USER app',
          'EXPOSE 8080',
          '',
          'HEALTHCHECK --interval=30s --timeout=3s --start-period=15s --retries=3 \\',
          '  CMD node -e "fetch(\'http://localhost:8080/healthz\').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"',
          '',
          '# No secrets are baked into the image; configuration arrives via the task role.',
          'CMD ["node", "dist/main.js"]',
        ].join('\n'),
      },
    ],
    grafanaDashboardJson: JSON.stringify({
      title: `${name} — service health`,
      tags: ['generated', 'slo'],
      refresh: '30s',
      panels: [
        { title: 'Traffic — requests/sec by outcome', type: 'timeseries', targets: [{ expr: 'sum(rate(requests_submitted_total[5m])) by (outcome)' }] },
        { title: 'Errors — 5xx ratio (SLO 0.1%)', type: 'timeseries', targets: [{ expr: 'sum(rate(requests_submitted_total{outcome="error"}[5m])) / sum(rate(requests_submitted_total[5m]))' }], thresholds: [{ value: 0.001, colorMode: 'critical' }] },
        { title: 'Latency — p95 / p99 (SLO 300ms / 500ms)', type: 'timeseries', targets: [{ expr: 'histogram_quantile(0.95, sum(rate(request_submit_duration_seconds_bucket[5m])) by (le))' }, { expr: 'histogram_quantile(0.99, sum(rate(request_submit_duration_seconds_bucket[5m])) by (le))' }] },
        { title: 'Saturation — task CPU and queue depth', type: 'timeseries', targets: [{ expr: 'avg(ecs_task_cpu_utilization)' }, { expr: 'max(queue_depth)' }] },
        { title: 'Dependency — ledger failures and breaker state', type: 'timeseries', targets: [{ expr: 'sum(rate(ledger_posting_failures_total[5m])) by (reason)' }] },
        { title: 'DLQ depth (alerts above 0 for 15m)', type: 'stat', targets: [{ expr: 'max(dlq_depth)' }] },
        { title: 'Business KPI — straight-through-processing rate', type: 'stat', targets: [{ expr: 'sum(rate(requests_submitted_total{outcome="completed"}[1h])) / sum(rate(requests_submitted_total[1h]))' }] },
        { title: 'SLO error budget burn rate', type: 'timeseries', targets: [{ expr: '(1 - (sum(rate(requests_submitted_total{outcome="completed"}[1h])) / sum(rate(requests_submitted_total[1h])))) / 0.001' }] },
      ],
    }),
    pipelineStages: [
      { name: 'checkout', purpose: 'Fetch source at the tested commit', blocking: true, tools: ['actions/checkout'] },
      { name: 'lint', purpose: 'Static style + type checks', blocking: true, tools: ['eslint', 'tsc'] },
      { name: 'build', purpose: 'Compile and produce the container image', blocking: true, tools: ['docker buildx'] },
      { name: 'test', purpose: 'Unit + integration suites with coverage gate', blocking: true, tools: ['vitest', 'testcontainers'] },
      { name: 'snyk-scan', purpose: 'SCA — fail on High/Critical dependency CVEs', blocking: true, tools: ['snyk'] },
      { name: 'inspector-scan', purpose: 'Image + IaC scan', blocking: true, tools: ['trivy', 'amazon-inspector'] },
      { name: 'deploy', purpose: 'Progressive canary to prod with approval', blocking: false, tools: ['aws ecs', 'codedeploy'] },
    ],
    securityGates: [
      'SAST (Semgrep) — blocking on new high findings',
      'SCA (Snyk) — blocking on High/Critical CVEs',
      'Secret scan (gitleaks) — blocking on any hit',
      'Image scan (Trivy) — blocking on High/Critical',
      'IaC scan (checkov) — blocking on failed policies',
    ],
    observabilitySlos: [
      { name: 'Availability', target: '99.9% monthly', alertThreshold: 'error budget 50%/90% burnt (multi-window)' },
      { name: 'Latency p99', target: '< 500 ms (submission)', alertThreshold: 'p99 > 500 ms for 10 min' },
      { name: 'Error ratio', target: '< 0.1%', alertThreshold: '5xx ratio > 0.1% for 5 min' },
      { name: 'DLQ depth', target: '0', alertThreshold: 'depth > 0 for 15 min' },
    ],
    rolloutStrategy:
      'Progressive canary via CodeDeploy: 10% for 10 min, 50% for 10 min, then 100%, with automated ' +
      'health checks on the golden signals at each step and manual approval gating production.',
    rollback:
      'Automated rollback to the previous task set on any SLO alarm during the canary; feature flags ' +
      'default off so a bad release is disabled without a redeploy.',
  });
}

export function phase6(topic: string, seed: string): string {
  const name = svc(topic);
  const id = slug(topic);
  return JSON.stringify({
    branch: `feat/${id}-submission-api`,
    commitMessage: `feat(${id}): idempotent submission API with outbox publishing\n\nImplements FR-1, FR-2 and FR-6: scope-checked submission with idempotency\nreplay, RFC 7807 error responses, transactional outbox and audit emission.`,
    designNotes:
      'Hexagonal (ports & adapters): the controller and persistence are adapters around a ' +
      'framework-free domain core, so business rules are unit-testable without I/O. Repository ' +
      'pattern isolates data access; the ledger is reached through a resilience-wrapped client ' +
      '(retry + timeout + circuit breaker). Transactional outbox guarantees atomic persist-and-publish.',
    codingStandards: [
      'Names follow the target-stack conventions; classes are nouns, methods are verbs.',
      'No business logic in controllers; single responsibility per class.',
      'All inputs validated at the boundary; domain types are immutable value objects.',
      'Typed, checked exceptions — no swallowed errors; failures map to the documented error taxonomy.',
      'No magic numbers/strings; configuration is injected, not hardcoded.',
    ],
    securityNotes: [
      'Parameterised queries only — no string-built SQL (SQL injection).',
      'Output is encoded and problem+json omits internals — no stack traces or PII leak.',
      'No secrets in source; credentials come from Secrets Manager via the task role.',
      'Authentication and scope authorisation enforced on every entry point; deny by default.',
      'Dependencies pinned and scanned (SCA) in CI; least-privilege IAM on the task role.',
    ],
    prTitle: `feat(${id}): idempotent submission API`,
    prBody: [
      '## What changed',
      '- Adds `POST /v1/requests` with scope enforcement, schema validation and idempotent replay.',
      '- Persists the request and its outbox row in a single transaction so a publish failure cannot lose work.',
      '- Emits an audit event for every state transition with the correlation id.',
      '- Returns RFC 7807 problem+json for all failure modes; no stack traces leave the process.',
      '',
      '## Why',
      'FR-1 requires submissions to be safely retryable by clients, and ADR-001 decouples processing',
      'from the ledger so our availability is not bounded by a 99.5% dependency.',
      '',
      '## Risk and rollback',
      'Risk: low — the endpoint sits behind the `' + id + '-enabled` flag and is additive; no schema',
      'changes are destructive. Rollback: disable the flag, then revert this commit if required.',
      '',
      '## Verification',
      '- Unit and integration suites pass (coverage 86% lines / 74% branches on changed code).',
      '- Idempotent replay, validation, authorisation and ledger-outage scenarios verified end to end.',
      '- k6 steady-state run met p95 268 ms / p99 431 ms at 200 rps.',
    ].join('\n'),
    checklist: [
      'Contract change is additive and the OpenAPI document lints clean',
      'Error responses follow RFC 7807 and omit internal detail',
      'Idempotency verified under concurrent submission',
      'Structured logs carry the correlation id and contain no PII or secrets',
      'Metrics and trace spans named in the LLD are emitted',
      'Feature flag defaults to off; rollback path documented',
      'Tests cover happy path, boundary and failure cases',
    ],
    files: [
      {
        path: 'src/api/request.controller.ts',
        content: [
          "import { randomUUID } from 'node:crypto';",
          "import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';",
          "import { RequestCreateSchema, type RequestCreate } from '../domain/request.schema.js';",
          "import { ConflictError, ValidationError } from '../domain/errors.js';",
          "import type { RequestService } from '../application/request.service.js';",
          '',
          '/**',
          ' * HTTP binding only: authorisation, deserialisation and response shaping.',
          ' * All business rules live in the application layer.',
          ' */',
          'export function registerRequestRoutes(app: FastifyInstance, service: RequestService): void {',
          "  app.post('/v1/requests', {",
          '    schema: { body: RequestCreateSchema },',
          '    config: { requiredScope: "requests:write" },',
          '  }, async (req: FastifyRequest<{ Body: RequestCreate }>, reply: FastifyReply) => {',
          "    const idempotencyKey = req.headers['idempotency-key'];",
          "    if (typeof idempotencyKey !== 'string' || idempotencyKey.length === 0) {",
          "      throw new ValidationError([{ field: 'Idempotency-Key', rule: 'required' }]);",
          '    }',
          '',
          '    const correlationId = (req.headers["x-correlation-id"] as string) ?? randomUUID();',
          '    const result = await service.submit({',
          '      payload: req.body,',
          '      idempotencyKey,',
          '      actor: req.user.subject,',
          '      correlationId,',
          '    });',
          '',
          '    return reply',
          '      .code(201)',
          "      .header('Location', `/v1/requests/${result.id}`)",
          "      .header('Idempotent-Replay', String(result.replayed))",
          '      .send(result.request);',
          '  });',
          '',
          "  app.get('/v1/requests/:requestId', {",
          '    config: { requiredScope: "requests:read" },',
          '  }, async (req: FastifyRequest<{ Params: { requestId: string } }>, reply: FastifyReply) => {',
          '    const request = await service.findForActor(req.params.requestId, req.user.subject);',
          '    return reply.code(200).send(request);',
          '  });',
          '}',
        ].join('\n'),
      },
      {
        path: 'src/application/request.service.ts',
        content: [
          "import { createHash, randomUUID } from 'node:crypto';",
          "import type { AuditWriter } from '../infrastructure/audit.writer.js';",
          "import type { RequestRepository } from '../infrastructure/request.repository.js';",
          "import type { IdempotencyStore } from '../infrastructure/idempotency.store.js';",
          "import { ConflictError, NotFoundError } from '../domain/errors.js';",
          "import type { RequestCreate, StoredRequest } from '../domain/request.schema.js';",
          '',
          'export interface SubmitCommand {',
          '  readonly payload: RequestCreate;',
          '  readonly idempotencyKey: string;',
          '  readonly actor: string;',
          '  readonly correlationId: string;',
          '}',
          '',
          'const canonicalHash = (payload: RequestCreate): string =>',
          "  createHash('sha256').update(JSON.stringify(payload, Object.keys(payload).sort())).digest('hex');",
          '',
          '/**',
          ' * Submission use case. The request row and its outbox entry are written in one',
          ' * transaction so a publish failure can never lose accepted work (LLD §3).',
          ' */',
          'export class RequestService {',
          '  constructor(',
          '    private readonly repository: RequestRepository,',
          '    private readonly idempotency: IdempotencyStore,',
          '    private readonly audit: AuditWriter,',
          '  ) {}',
          '',
          '  async submit(command: SubmitCommand): Promise<{ id: string; request: StoredRequest; replayed: boolean }> {',
          '    const payloadHash = canonicalHash(command.payload);',
          '    const reserved = await this.idempotency.reserve(command.idempotencyKey, payloadHash);',
          '',
          '    if (!reserved.acquired) {',
          '      if (reserved.payloadHash !== payloadHash) {',
          "        throw new ConflictError('Idempotency-Key was reused with a different payload');",
          '      }',
          '      const existing = await this.repository.findById(reserved.requestId);',
          '      if (existing) return { id: existing.id, request: existing, replayed: true };',
          '    }',
          '',
          '    const request: StoredRequest = {',
          '      id: randomUUID(),',
          '      reference: command.payload.reference,',
          '      amount: command.payload.amount,',
          '      currency: command.payload.currency,',
          "      status: 'ACCEPTED',",
          '      createdAt: new Date().toISOString(),',
          '    };',
          '',
          '    // Single transaction: request + outbox. The relay publishes asynchronously.',
          '    await this.repository.insertWithOutbox(request, payloadHash, command.idempotencyKey);',
          '    await this.idempotency.bind(command.idempotencyKey, request.id);',
          '',
          '    await this.audit.record({',
          "      action: 'request.accepted',",
          '      actor: command.actor,',
          '      resourceId: request.id,',
          '      correlationId: command.correlationId,',
          "      before: null,",
          "      after: 'ACCEPTED',",
          '    });',
          '',
          '    return { id: request.id, request, replayed: false };',
          '  }',
          '',
          '  async findForActor(requestId: string, actor: string): Promise<StoredRequest> {',
          '    const request = await this.repository.findByIdForActor(requestId, actor);',
          '    // Absent-or-unauthorised are indistinguishable so existence is not disclosed.',
          "    if (!request) throw new NotFoundError('Request not found');",
          '    return request;',
          '  }',
          '}',
        ].join('\n'),
      },
      {
        path: 'src/infrastructure/ledger.client.ts',
        content: [
          "import { setTimeout as delay } from 'node:timers/promises';",
          "import { DependencyUnavailableError } from '../domain/errors.js';",
          '',
          'export interface LedgerPosting {',
          '  readonly requestId: string;',
          '  readonly amount: number;',
          '  readonly currency: string;',
          '}',
          '',
          '/** Resilience policy values come from the LLD §6 table. */',
          'const TIMEOUT_MS = Number(process.env.LEDGER_TIMEOUT_MS ?? 2000);',
          'const MAX_ATTEMPTS = 3;',
          'const BASE_BACKOFF_MS = 200;',
          'const BACKOFF_CAP_MS = 4000;',
          '',
          'export class LedgerClient {',
          '  private consecutiveFailures = 0;',
          '  private breakerOpenedAt: number | null = null;',
          '',
          '  constructor(private readonly baseUrl: string, private readonly tokenProvider: () => Promise<string>) {}',
          '',
          '  /** Posts idempotently: the request id is the ledger idempotency key. */',
          '  async post(posting: LedgerPosting): Promise<{ postingId: string }> {',
          '    if (this.isBreakerOpen()) {',
          "      throw new DependencyUnavailableError('Ledger circuit breaker is open');",
          '    }',
          '',
          '    let lastError: unknown;',
          '    for (let attempt = 0; attempt < MAX_ATTEMPTS; attempt++) {',
          '      try {',
          '        const response = await fetch(`${this.baseUrl}/postings`, {',
          "          method: 'POST',",
          '          headers: {',
          "            'Content-Type': 'application/json',",
          '            Authorization: `Bearer ${await this.tokenProvider()}`,',
          "            'Idempotency-Key': posting.requestId,",
          '          },',
          '          body: JSON.stringify(posting),',
          '          signal: AbortSignal.timeout(TIMEOUT_MS),',
          '        });',
          '',
          '        if (response.status >= 500) throw new Error(`ledger ${response.status}`);',
          '        if (!response.ok) {',
          '          // 4xx is deterministic — retrying cannot help, so fail fast.',
          '          throw new DependencyUnavailableError(`Ledger rejected the posting (${response.status})`);',
          '        }',
          '        this.consecutiveFailures = 0;',
          '        return (await response.json()) as { postingId: string };',
          '      } catch (error) {',
          '        lastError = error;',
          '        if (error instanceof DependencyUnavailableError) throw error;',
          '        if (attempt < MAX_ATTEMPTS - 1) {',
          '          // Exponential backoff with full jitter, capped (LLD §6).',
          '          const ceiling = Math.min(BASE_BACKOFF_MS * 2 ** attempt, BACKOFF_CAP_MS);',
          '          await delay(Math.random() * ceiling);',
          '        }',
          '      }',
          '    }',
          '',
          '    this.recordFailure();',
          "    throw new DependencyUnavailableError('Ledger unavailable after retries', { cause: lastError });",
          '  }',
          '',
          '  private isBreakerOpen(): boolean {',
          '    if (this.breakerOpenedAt === null) return false;',
          '    if (Date.now() - this.breakerOpenedAt > 30_000) {',
          '      this.breakerOpenedAt = null; // half-open: allow one probe through',
          '      this.consecutiveFailures = 0;',
          '      return false;',
          '    }',
          '    return true;',
          '  }',
          '',
          '  private recordFailure(): void {',
          '    this.consecutiveFailures += 1;',
          '    if (this.consecutiveFailures >= 5) this.breakerOpenedAt = Date.now();',
          '  }',
          '}',
          BUG_SEED,
        ].join('\n'),
      },
      {
        path: 'src/application/request.service.test.ts',
        content: [
          "import { describe, expect, it, vi } from 'vitest';",
          "import { RequestService } from './request.service.js';",
          "import { ConflictError, NotFoundError } from '../domain/errors.js';",
          '',
          "const payload = { reference: 'REQ-1001', amount: 1250.0, currency: 'GBP' } as const;",
          '',
          'function build(overrides: Partial<{ reserved: unknown; stored: unknown }> = {}) {',
          '  const repository = {',
          '    insertWithOutbox: vi.fn().mockResolvedValue(undefined),',
          '    findById: vi.fn().mockResolvedValue(overrides.stored ?? null),',
          '    findByIdForActor: vi.fn().mockResolvedValue(overrides.stored ?? null),',
          '  };',
          '  const idempotency = {',
          '    reserve: vi.fn().mockResolvedValue(overrides.reserved ?? { acquired: true }),',
          '    bind: vi.fn().mockResolvedValue(undefined),',
          '  };',
          "  const audit = { record: vi.fn().mockResolvedValue(undefined) };",
          '  return { service: new RequestService(repository as never, idempotency as never, audit as never), repository, idempotency, audit };',
          '}',
          '',
          "describe('RequestService.submit', () => {",
          "  it('persists the request with its outbox row and audits acceptance', async () => {",
          '    const { service, repository, audit } = build();',
          '',
          "    const result = await service.submit({ payload, idempotencyKey: 'K1', actor: 'client-a', correlationId: 'corr-1' });",
          '',
          '    expect(result.replayed).toBe(false);',
          "    expect(result.request.status).toBe('ACCEPTED');",
          '    expect(repository.insertWithOutbox).toHaveBeenCalledOnce();',
          "    expect(audit.record).toHaveBeenCalledWith(expect.objectContaining({ action: 'request.accepted', correlationId: 'corr-1' }));",
          '  });',
          '',
          "  it('replays the original response when the same key and payload are resubmitted', async () => {",
          "    const stored = { id: 'req-1', reference: 'REQ-1001', amount: 1250.0, currency: 'GBP', status: 'ACCEPTED', createdAt: '2026-01-01T00:00:00Z' };",
          '    const { service, repository } = build({',
          "      reserved: { acquired: false, requestId: 'req-1', payloadHash: undefined },",
          '      stored,',
          '    });',
          '    // Hash matches because the same payload is submitted.',
          "    repository.findById.mockResolvedValue(stored);",
          '',
          '    const { service: s2 } = build({ reserved: { acquired: false, requestId: "req-1", payloadHash: "mismatch" } });',
          '    await expect(',
          "      s2.submit({ payload, idempotencyKey: 'K1', actor: 'client-a', correlationId: 'corr-2' }),",
          '    ).rejects.toBeInstanceOf(ConflictError);',
          '  });',
          '',
          "  it('does not disclose existence of another actor\\'s request', async () => {",
          '    const { service } = build({ stored: null });',
          "    await expect(service.findForActor('req-9', 'client-b')).rejects.toBeInstanceOf(NotFoundError);",
          '  });',
          '});',
        ].join('\n'),
      },
    ],
  });
}
