"""Living specs and design deltas — pure, deterministic, no I/O.

A living spec is one markdown file per component with `## Section` headings. A sprint expresses its design
changes as a DELTA (add / replace / remove a section). `merge_delta` applies a delta without ever overwriting
work silently: a change that was authored against an older version of a section is reported as a conflict."""

from __future__ import annotations

import hashlib
import re
from typing import Any, Literal

from pydantic import BaseModel, Field

MAX_SECTION_CHARS = 20_000
MAX_SPEC_BYTES = 200_000
MAX_CHANGES = 40
_COMPONENT = re.compile(r"^[a-z0-9][a-z0-9_.-]{0,39}$")
_HEADING = re.compile(r"^##\s+(.+?)\s*#*\s*$")
SPEC_BANNER = "<!-- GENERATED BY DEVMIND — DO NOT EDIT. Changes arrive as reviewed sprint deltas. -->"


class SpecChange(BaseModel):
    component: str
    section: str
    op: Literal["add", "replace", "remove"] = "replace"
    content: str = ""
    rationale: str = ""
    baseHash: str | None = None       # hash of the section as the author last saw it (None = unchecked)


class DesignDelta(BaseModel):
    summary: str = ""
    changes: list[SpecChange] = Field(default_factory=list)


def component_slug(name: str) -> str:
    return re.sub(r"[^a-z0-9_.-]+", "-", name.strip().lower()).strip("-")[:40]


def section_name(name: str) -> str:
    return " ".join(name.replace("#", " ").split())[:80]


def section_hash(body: str) -> str:
    return hashlib.sha256(" ".join(body.split()).encode("utf-8")).hexdigest()[:12]


def parse_spec(md: str) -> tuple[str, dict[str, str]]:
    """(title line, ordered {section: body}). Tolerates a missing title and the generated banner."""
    title = ""
    sections: dict[str, str] = {}
    current: str | None = None
    buf: list[str] = []
    for line in md.splitlines():
        if line.startswith("<!--") and "DEVMIND" in line.upper():
            continue
        if line.startswith("# ") and not title and current is None:
            title = line[2:].strip()
            continue
        m = _HEADING.match(line)
        if m:
            if current is not None:
                sections[current] = "\n".join(buf).strip()
            current, buf = section_name(m.group(1)), []
        elif current is not None:
            buf.append(line)
    if current is not None:
        sections[current] = "\n".join(buf).strip()
    return title, sections


def render_spec(component: str, title: str, sections: dict[str, str]) -> str:
    out = [SPEC_BANNER, f"# {title or component}", ""]
    for name, body in sections.items():
        out += [f"## {name}", "", body.strip(), ""]
    return "\n".join(out).rstrip() + "\n"


def sanitise_delta(delta: DesignDelta, *, known_components: set[str] | None = None) -> tuple[DesignDelta, list[str]]:
    """Drop malformed changes; never trust the model's component/section strings."""
    warnings: list[str] = []
    seen: set[tuple[str, str]] = set()
    out: list[SpecChange] = []
    for i, c in enumerate(delta.changes[:MAX_CHANGES], start=1):
        comp = component_slug(c.component)
        sec = section_name(c.section)
        if not _COMPONENT.match(comp):
            warnings.append(f"change {i}: invalid component '{c.component}' — ignored")
            continue
        if not sec:
            warnings.append(f"change {i}: no section name — ignored")
            continue
        if known_components is not None and comp not in known_components:
            warnings.append(f"change {i}: component '{comp}' is not touched by this sprint — ignored")
            continue
        if (comp, sec.lower()) in seen:
            warnings.append(f"change {i}: '{comp}/{sec}' appears twice — second ignored")
            continue
        seen.add((comp, sec.lower()))
        content = c.content.strip()
        if c.op != "remove" and not content:
            warnings.append(f"change {i}: '{comp}/{sec}' has no content — ignored")
            continue
        bad = next((ln for ln in content.splitlines()
                    if re.match(r"^#{1,2}\s", ln) or (ln.lstrip().startswith("<!--") and "DEVMIND" in ln.upper())), None)
        if bad is not None:               # would corrupt the spec's structure when re-parsed
            warnings.append(f"change {i}: '{comp}/{sec}' contains a level-1/2 heading or a DevMind banner "
                            f"({bad.strip()[:40]!r}) — ignored")
            continue
        if len(content) > MAX_SECTION_CHARS:
            warnings.append(f"change {i}: '{comp}/{sec}' is longer than {MAX_SECTION_CHARS} characters — ignored")
            continue
        out.append(SpecChange(component=comp, section=sec, op=c.op, content=content,
                              rationale=" ".join(c.rationale.split())[:300], baseHash=c.baseHash))
    if len(delta.changes) > MAX_CHANGES:
        warnings.append(f"{len(delta.changes) - MAX_CHANGES} change(s) beyond the limit of {MAX_CHANGES} were dropped")
    return DesignDelta(summary=" ".join(delta.summary.split())[:600], changes=out), warnings


def merge_delta(spec_md: str | None, component: str, changes: list[SpecChange]) -> tuple[str, list[dict[str, Any]]]:
    """Apply the changes for ONE component. Returns (new markdown, per-change results).
    Result status: applied | unchanged | conflict. A conflict never modifies the spec."""
    title, sections = parse_spec(spec_md) if spec_md else (component, {})
    results: list[dict[str, Any]] = []
    for c in changes:
        key = next((k for k in sections if k.lower() == c.section.lower()), None)
        res = {"component": component, "section": c.section, "op": c.op}
        if c.op == "add":
            if key is not None:
                same = section_hash(sections[key]) == section_hash(c.content)
                results.append({**res, "status": "unchanged" if same else "conflict",
                                **({} if same else {"reason": "the section already exists; use replace"})})
                continue
            sections[c.section] = c.content
            results.append({**res, "status": "applied"})
            continue
        if key is None:
            results.append({**res, "status": "conflict", "reason": "the section no longer exists"})
            continue
        current = section_hash(sections[key])
        if c.op == "replace" and current == section_hash(c.content):    # a replay of an applied change
            results.append({**res, "status": "unchanged"})
            continue
        if not c.baseHash:                # a blind overwrite/removal could destroy a human-reviewed section
            results.append({**res, "status": "conflict", "currentHash": current,
                            "reason": f"{c.op} needs the baseHash of the section it was written against"})
            continue
        if c.baseHash != current:
            results.append({**res, "status": "conflict", "currentHash": current,
                            "reason": "the section changed after this delta was written"})
            continue
        if c.op == "remove":
            del sections[key]
            results.append({**res, "status": "applied"})
        elif current == section_hash(c.content):
            results.append({**res, "status": "unchanged"})
        else:
            sections[key] = c.content
            results.append({**res, "status": "applied"})
    new = render_spec(component, title or component, sections)
    if len(new.encode("utf-8")) > MAX_SPEC_BYTES:
        return spec_md or render_spec(component, title or component, {}), [
            {"component": component, "section": "*", "op": "all", "status": "conflict",
             "reason": f"the spec would exceed {MAX_SPEC_BYTES} bytes"}]
    return new, results


def spec_path(component: str, release: str) -> str:
    """Living specs belong to a RELEASE: releases are independent components of the project."""
    return f".devmind/releases/{release}/specs/{component}.md"


def group_by_component(changes: list[SpecChange]) -> dict[str, list[SpecChange]]:
    out: dict[str, list[SpecChange]] = {}
    for c in changes:
        out.setdefault(c.component, []).append(c)
    return out


def render_delta_md(delta: DesignDelta, warnings: list[str], stage_name: str) -> str:
    lines = [f"# {stage_name or 'Design delta'}", "", delta.summary or "_No summary._", ""]
    if warnings:
        lines += ["## Needs attention", *[f"- {w}" for w in warnings], ""]
    for comp, changes in group_by_component(delta.changes).items():
        lines += [f"## {comp}", ""]
        for c in changes:
            lines.append(f"### {c.op.upper()} · {c.section}")
            if c.rationale:
                lines += ["", f"_Why:_ {c.rationale}"]
            if c.content:
                lines += ["", c.content]
            lines.append("")
    if not delta.changes:
        lines += ["_No design changes this sprint._", ""]
    return "\n".join(lines)
